# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Programming\Repositories\PyFANS\PyFANS\UI\UI_VoltageControl.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_VoltageControl(object):
    def setupUi(self, VoltageControl):
        VoltageControl.setObjectName(_fromUtf8("VoltageControl"))
        VoltageControl.resize(829, 534)
        self.verticalLayout_2 = QtGui.QVBoxLayout(VoltageControl)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(VoltageControl)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.ui_controller_resource = QtGui.QComboBox(VoltageControl)
        self.ui_controller_resource.setObjectName(_fromUtf8("ui_controller_resource"))
        self.horizontalLayout_2.addWidget(self.ui_controller_resource)
        self.ui_initialize = QtGui.QPushButton(VoltageControl)
        self.ui_initialize.setObjectName(_fromUtf8("ui_initialize"))
        self.horizontalLayout_2.addWidget(self.ui_initialize)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.groupBox_3 = QtGui.QGroupBox(VoltageControl)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.ui_drain_source_voltage = QtGui.QLineEdit(self.groupBox_3)
        self.ui_drain_source_voltage.setReadOnly(True)
        self.ui_drain_source_voltage.setObjectName(_fromUtf8("ui_drain_source_voltage"))
        self.gridLayout_3.addWidget(self.ui_drain_source_voltage, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 0, 2, 1, 1)
        self.ui_load_resistance = QtGui.QLineEdit(self.groupBox_3)
        self.ui_load_resistance.setObjectName(_fromUtf8("ui_load_resistance"))
        self.gridLayout_3.addWidget(self.ui_load_resistance, 0, 3, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.ui_gate_voltage = QtGui.QLineEdit(self.groupBox_3)
        self.ui_gate_voltage.setReadOnly(True)
        self.ui_gate_voltage.setObjectName(_fromUtf8("ui_gate_voltage"))
        self.gridLayout_3.addWidget(self.ui_gate_voltage, 1, 1, 1, 1)
        self.ui_set_load_resistance = QtGui.QPushButton(self.groupBox_3)
        self.ui_set_load_resistance.setObjectName(_fromUtf8("ui_set_load_resistance"))
        self.gridLayout_3.addWidget(self.ui_set_load_resistance, 1, 2, 1, 2)
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 2, 0, 1, 1)
        self.ui_main_voltage = QtGui.QLineEdit(self.groupBox_3)
        self.ui_main_voltage.setReadOnly(True)
        self.ui_main_voltage.setObjectName(_fromUtf8("ui_main_voltage"))
        self.gridLayout_3.addWidget(self.ui_main_voltage, 2, 1, 1, 1)
        self.ui_start_single_measurement = QtGui.QPushButton(self.groupBox_3)
        self.ui_start_single_measurement.setObjectName(_fromUtf8("ui_start_single_measurement"))
        self.gridLayout_3.addWidget(self.ui_start_single_measurement, 2, 2, 1, 2)
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 3, 0, 1, 1)
        self.ui_drain_current = QtGui.QLineEdit(self.groupBox_3)
        self.ui_drain_current.setReadOnly(True)
        self.ui_drain_current.setObjectName(_fromUtf8("ui_drain_current"))
        self.gridLayout_3.addWidget(self.ui_drain_current, 3, 1, 1, 1)
        self.ui_start_repetitive_measurement = QtGui.QPushButton(self.groupBox_3)
        self.ui_start_repetitive_measurement.setObjectName(_fromUtf8("ui_start_repetitive_measurement"))
        self.gridLayout_3.addWidget(self.ui_start_repetitive_measurement, 3, 2, 1, 2)
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 4, 0, 1, 1)
        self.ui_sample_resistence = QtGui.QLineEdit(self.groupBox_3)
        self.ui_sample_resistence.setReadOnly(True)
        self.ui_sample_resistence.setObjectName(_fromUtf8("ui_sample_resistence"))
        self.gridLayout_3.addWidget(self.ui_sample_resistence, 4, 1, 1, 1)
        self.ui_stop_repetitive_measurement = QtGui.QPushButton(self.groupBox_3)
        self.ui_stop_repetitive_measurement.setObjectName(_fromUtf8("ui_stop_repetitive_measurement"))
        self.gridLayout_3.addWidget(self.ui_stop_repetitive_measurement, 4, 2, 1, 2)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox = QtGui.QGroupBox(VoltageControl)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 2, 1)
        self.line = QtGui.QFrame(self.groupBox)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 0, 2, 3, 2)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 4, 2, 1)
        self.line_3 = QtGui.QFrame(self.groupBox)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 0, 7, 3, 2)
        self.ui_ds_positiv = QtGui.QPushButton(self.groupBox)
        self.ui_ds_positiv.setObjectName(_fromUtf8("ui_ds_positiv"))
        self.gridLayout.addWidget(self.ui_ds_positiv, 2, 0, 1, 1)
        self.ui_ds_negativ = QtGui.QPushButton(self.groupBox)
        self.ui_ds_negativ.setObjectName(_fromUtf8("ui_ds_negativ"))
        self.gridLayout.addWidget(self.ui_ds_negativ, 2, 1, 1, 1)
        self.ui_ds_move_left_fast = QtGui.QPushButton(self.groupBox)
        self.ui_ds_move_left_fast.setObjectName(_fromUtf8("ui_ds_move_left_fast"))
        self.gridLayout.addWidget(self.ui_ds_move_left_fast, 2, 3, 1, 1)
        self.ui_ds_move_left = QtGui.QPushButton(self.groupBox)
        self.ui_ds_move_left.setObjectName(_fromUtf8("ui_ds_move_left"))
        self.gridLayout.addWidget(self.ui_ds_move_left, 2, 4, 1, 1)
        self.ui_move_right = QtGui.QPushButton(self.groupBox)
        self.ui_move_right.setObjectName(_fromUtf8("ui_move_right"))
        self.gridLayout.addWidget(self.ui_move_right, 2, 5, 1, 1)
        self.ui_move_right_fast = QtGui.QPushButton(self.groupBox)
        self.ui_move_right_fast.setObjectName(_fromUtf8("ui_move_right_fast"))
        self.gridLayout.addWidget(self.ui_move_right_fast, 2, 6, 1, 1)
        self.ui_ds_value = QtGui.QLineEdit(self.groupBox)
        self.ui_ds_value.setObjectName(_fromUtf8("ui_ds_value"))
        self.gridLayout.addWidget(self.ui_ds_value, 2, 9, 1, 1)
        self.ui_ds_set_value = QtGui.QPushButton(self.groupBox)
        self.ui_ds_set_value.setObjectName(_fromUtf8("ui_ds_set_value"))
        self.gridLayout.addWidget(self.ui_ds_set_value, 2, 10, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(VoltageControl)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.groupBox_2)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_2.addWidget(self.line_2, 0, 2, 2, 2)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 4, 1, 1)
        self.line_4 = QtGui.QFrame(self.groupBox_2)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_2.addWidget(self.line_4, 0, 7, 2, 1)
        self.ui_gs_positiv = QtGui.QPushButton(self.groupBox_2)
        self.ui_gs_positiv.setObjectName(_fromUtf8("ui_gs_positiv"))
        self.gridLayout_2.addWidget(self.ui_gs_positiv, 1, 0, 1, 1)
        self.ui_gs_negativ = QtGui.QPushButton(self.groupBox_2)
        self.ui_gs_negativ.setObjectName(_fromUtf8("ui_gs_negativ"))
        self.gridLayout_2.addWidget(self.ui_gs_negativ, 1, 1, 1, 1)
        self.ui_gs_move_left_fast = QtGui.QPushButton(self.groupBox_2)
        self.ui_gs_move_left_fast.setObjectName(_fromUtf8("ui_gs_move_left_fast"))
        self.gridLayout_2.addWidget(self.ui_gs_move_left_fast, 1, 3, 1, 1)
        self.ui_gs_move_left = QtGui.QPushButton(self.groupBox_2)
        self.ui_gs_move_left.setObjectName(_fromUtf8("ui_gs_move_left"))
        self.gridLayout_2.addWidget(self.ui_gs_move_left, 1, 4, 1, 1)
        self.ui_gs_move_right = QtGui.QPushButton(self.groupBox_2)
        self.ui_gs_move_right.setObjectName(_fromUtf8("ui_gs_move_right"))
        self.gridLayout_2.addWidget(self.ui_gs_move_right, 1, 5, 1, 1)
        self.ui_gs_move_right_fast = QtGui.QPushButton(self.groupBox_2)
        self.ui_gs_move_right_fast.setObjectName(_fromUtf8("ui_gs_move_right_fast"))
        self.gridLayout_2.addWidget(self.ui_gs_move_right_fast, 1, 6, 1, 1)
        self.ui_gs_value = QtGui.QLineEdit(self.groupBox_2)
        self.ui_gs_value.setObjectName(_fromUtf8("ui_gs_value"))
        self.gridLayout_2.addWidget(self.ui_gs_value, 1, 8, 1, 1)
        self.ui_gs_set_value = QtGui.QPushButton(self.groupBox_2)
        self.ui_gs_set_value.setObjectName(_fromUtf8("ui_gs_set_value"))
        self.gridLayout_2.addWidget(self.ui_gs_set_value, 1, 9, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_4 = QtGui.QGroupBox(VoltageControl)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_8 = QtGui.QLabel(self.groupBox_4)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout.addWidget(self.label_8)
        self.ui_selected_dut = QtGui.QSpinBox(self.groupBox_4)
        self.ui_selected_dut.setMinimum(1)
        self.ui_selected_dut.setMaximum(32)
        self.ui_selected_dut.setObjectName(_fromUtf8("ui_selected_dut"))
        self.horizontalLayout.addWidget(self.ui_selected_dut)
        self.ui_switch_dut = QtGui.QPushButton(self.groupBox_4)
        self.ui_switch_dut.setObjectName(_fromUtf8("ui_switch_dut"))
        self.horizontalLayout.addWidget(self.ui_switch_dut)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.groupBox_4)

        self.retranslateUi(VoltageControl)
        QtCore.QMetaObject.connectSlotsByName(VoltageControl)

    def retranslateUi(self, VoltageControl):
        VoltageControl.setWindowTitle(_translate("VoltageControl", "Voltage control application", None))
        self.label.setText(_translate("VoltageControl", "Agilent Controller", None))
        self.ui_initialize.setText(_translate("VoltageControl", "Initialize", None))
        self.groupBox_3.setTitle(_translate("VoltageControl", "Feedback data", None))
        self.label_6.setText(_translate("VoltageControl", "Drain-Source Voltage", None))
        self.label_7.setText(_translate("VoltageControl", "Load resistance", None))
        self.label_9.setText(_translate("VoltageControl", "Gate-Source Voltage", None))
        self.ui_set_load_resistance.setText(_translate("VoltageControl", "Set load resistance", None))
        self.label_10.setText(_translate("VoltageControl", "Main Voltage", None))
        self.ui_start_single_measurement.setText(_translate("VoltageControl", "Single measurement", None))
        self.label_11.setText(_translate("VoltageControl", "Drain Current", None))
        self.ui_start_repetitive_measurement.setText(_translate("VoltageControl", "Start repetitive", None))
        self.label_12.setText(_translate("VoltageControl", "Sample Resistance", None))
        self.ui_stop_repetitive_measurement.setText(_translate("VoltageControl", "Stop repetitive", None))
        self.groupBox.setTitle(_translate("VoltageControl", "Drain-Source Voltage Control", None))
        self.label_2.setText(_translate("VoltageControl", "Polarity", None))
        self.label_3.setText(_translate("VoltageControl", "Motor Movement", None))
        self.ui_ds_positiv.setText(_translate("VoltageControl", "+", None))
        self.ui_ds_negativ.setText(_translate("VoltageControl", "-", None))
        self.ui_ds_move_left_fast.setText(_translate("VoltageControl", "<<", None))
        self.ui_ds_move_left.setText(_translate("VoltageControl", "<", None))
        self.ui_move_right.setText(_translate("VoltageControl", ">", None))
        self.ui_move_right_fast.setText(_translate("VoltageControl", ">>", None))
        self.ui_ds_set_value.setText(_translate("VoltageControl", "Go", None))
        self.groupBox_2.setTitle(_translate("VoltageControl", "Gate-Source Voltage Control", None))
        self.label_4.setText(_translate("VoltageControl", "Polarity", None))
        self.label_5.setText(_translate("VoltageControl", "Motor Movement", None))
        self.ui_gs_positiv.setText(_translate("VoltageControl", "+", None))
        self.ui_gs_negativ.setText(_translate("VoltageControl", "-", None))
        self.ui_gs_move_left_fast.setText(_translate("VoltageControl", "<<", None))
        self.ui_gs_move_left.setText(_translate("VoltageControl", "<", None))
        self.ui_gs_move_right.setText(_translate("VoltageControl", ">", None))
        self.ui_gs_move_right_fast.setText(_translate("VoltageControl", ">>", None))
        self.ui_gs_set_value.setText(_translate("VoltageControl", "Go", None))
        self.groupBox_4.setTitle(_translate("VoltageControl", "DUT selector", None))
        self.label_8.setText(_translate("VoltageControl", "Select transistor", None))
        self.ui_switch_dut.setText(_translate("VoltageControl", "Switch", None))

