# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainForm.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName(_fromUtf8("mainWindow"))
        mainWindow.resize(917, 776)
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setMargin(3)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.timetracePlot = PlotWidget(self.centralwidget)
        self.timetracePlot.setMinimumSize(QtCore.QSize(10, 10))
        self.timetracePlot.setObjectName(_fromUtf8("timetracePlot"))
        self.verticalLayout.addWidget(self.timetracePlot)
        self.noisePlot = PlotWidget(self.centralwidget)
        self.noisePlot.setObjectName(_fromUtf8("noisePlot"))
        self.verticalLayout.addWidget(self.noisePlot)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 917, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuWindow = QtGui.QMenu(self.menubar)
        self.menuWindow.setObjectName(_fromUtf8("menuWindow"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuSave_2 = QtGui.QMenu(self.menuSettings)
        self.menuSave_2.setObjectName(_fromUtf8("menuSave_2"))
        self.menuLoad_2 = QtGui.QMenu(self.menuSettings)
        self.menuLoad_2.setObjectName(_fromUtf8("menuLoad_2"))
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(mainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        mainWindow.setStatusBar(self.statusbar)
        self.controlsWidget = QtGui.QDockWidget(mainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlsWidget.sizePolicy().hasHeightForWidth())
        self.controlsWidget.setSizePolicy(sizePolicy)
        self.controlsWidget.setMinimumSize(QtCore.QSize(159, 77))
        self.controlsWidget.setMaximumSize(QtCore.QSize(200, 100))
        self.controlsWidget.setAcceptDrops(False)
        self.controlsWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.controlsWidget.setObjectName(_fromUtf8("controlsWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setEnabled(True)
        self.dockWidgetContents.setBaseSize(QtCore.QSize(0, 0))
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setMargin(3)
        self.gridLayout.setSpacing(3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.stopButton = QtGui.QPushButton(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopButton.sizePolicy().hasHeightForWidth())
        self.stopButton.setSizePolicy(sizePolicy)
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.gridLayout.addWidget(self.stopButton, 1, 1, 1, 1)
        self.singleShotButton = QtGui.QPushButton(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.singleShotButton.sizePolicy().hasHeightForWidth())
        self.singleShotButton.setSizePolicy(sizePolicy)
        self.singleShotButton.setObjectName(_fromUtf8("singleShotButton"))
        self.gridLayout.addWidget(self.singleShotButton, 3, 0, 1, 2)
        self.startButton = QtGui.QPushButton(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)
        self.startButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.gridLayout.addWidget(self.startButton, 1, 0, 1, 1)
        self.controlsWidget.setWidget(self.dockWidgetContents)
        mainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.controlsWidget)
        self.frequenciesWidget = QtGui.QDockWidget(mainWindow)
        self.frequenciesWidget.setMinimumSize(QtCore.QSize(191, 200))
        self.frequenciesWidget.setMaximumSize(QtCore.QSize(200, 200))
        self.frequenciesWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.frequenciesWidget.setObjectName(_fromUtf8("frequenciesWidget"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pushButton = QtGui.QPushButton(self.dockWidgetContents_2)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_2.addWidget(self.pushButton, 5, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.dockWidgetContents_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 4, 0, 1, 1)
        self.spinBox = QtGui.QSpinBox(self.dockWidgetContents_2)
        self.spinBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.spinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox.setMinimum(100)
        self.spinBox.setMaximum(500000)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.gridLayout_2.addWidget(self.spinBox, 3, 1, 1, 1)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.dockWidgetContents_2)
        self.doubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox.setSpecialValueText(_fromUtf8(""))
        self.doubleSpinBox.setAccelerated(False)
        self.doubleSpinBox.setDecimals(1)
        self.doubleSpinBox.setSingleStep(0.1)
        self.doubleSpinBox.setProperty("value", 100.0)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.gridLayout_2.addWidget(self.doubleSpinBox, 4, 1, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.dockWidgetContents_2)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_2.addWidget(self.pushButton_2, 5, 1, 1, 1)
        self.label = QtGui.QLabel(self.dockWidgetContents_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 1)
        self.listWidget = QtGui.QListWidget(self.dockWidgetContents_2)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        self.gridLayout_2.addWidget(self.listWidget, 2, 1, 1, 1)
        self.widget = FrequencyWidget(self.dockWidgetContents_2)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_2.addWidget(self.widget, 2, 0, 1, 1)
        self.frequenciesWidget.setWidget(self.dockWidgetContents_2)
        mainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.frequenciesWidget)
        self.actionWorkingFolder = QtGui.QAction(mainWindow)
        self.actionWorkingFolder.setObjectName(_fromUtf8("actionWorkingFolder"))
        self.actionExit = QtGui.QAction(mainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionRestore_windows = QtGui.QAction(mainWindow)
        self.actionRestore_windows.setObjectName(_fromUtf8("actionRestore_windows"))
        self.actionAbout = QtGui.QAction(mainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionFrequencySettings = QtGui.QAction(mainWindow)
        self.actionFrequencySettings.setObjectName(_fromUtf8("actionFrequencySettings"))
        self.actionAllSettings = QtGui.QAction(mainWindow)
        self.actionAllSettings.setObjectName(_fromUtf8("actionAllSettings"))
        self.actionFrequency_range = QtGui.QAction(mainWindow)
        self.actionFrequency_range.setObjectName(_fromUtf8("actionFrequency_range"))
        self.actionVoltage_range = QtGui.QAction(mainWindow)
        self.actionVoltage_range.setObjectName(_fromUtf8("actionVoltage_range"))
        self.actionAll = QtGui.QAction(mainWindow)
        self.actionAll.setObjectName(_fromUtf8("actionAll"))
        self.actionSaveAll = QtGui.QAction(mainWindow)
        self.actionSaveAll.setObjectName(_fromUtf8("actionSaveAll"))
        self.actionFrequencies = QtGui.QAction(mainWindow)
        self.actionFrequencies.setObjectName(_fromUtf8("actionFrequencies"))
        self.actionVoltages = QtGui.QAction(mainWindow)
        self.actionVoltages.setObjectName(_fromUtf8("actionVoltages"))
        self.actionAll_2 = QtGui.QAction(mainWindow)
        self.actionAll_2.setObjectName(_fromUtf8("actionAll_2"))
        self.actionFrequencies_2 = QtGui.QAction(mainWindow)
        self.actionFrequencies_2.setObjectName(_fromUtf8("actionFrequencies_2"))
        self.actionVoltages_2 = QtGui.QAction(mainWindow)
        self.actionVoltages_2.setObjectName(_fromUtf8("actionVoltages_2"))
        self.actionAll_3 = QtGui.QAction(mainWindow)
        self.actionAll_3.setObjectName(_fromUtf8("actionAll_3"))
        self.menuFile.addAction(self.actionWorkingFolder)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuWindow.addAction(self.actionRestore_windows)
        self.menuHelp.addAction(self.actionAbout)
        self.menuSave_2.addAction(self.actionFrequencies)
        self.menuSave_2.addAction(self.actionVoltages)
        self.menuSave_2.addAction(self.actionAll_2)
        self.menuLoad_2.addAction(self.actionFrequencies_2)
        self.menuLoad_2.addAction(self.actionVoltages_2)
        self.menuLoad_2.addAction(self.actionAll_3)
        self.menuSettings.addAction(self.menuSave_2.menuAction())
        self.menuSettings.addAction(self.menuLoad_2.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(_translate("mainWindow", "PyFANS", None))
        self.menuFile.setTitle(_translate("mainWindow", "File", None))
        self.menuWindow.setTitle(_translate("mainWindow", "Window", None))
        self.menuHelp.setTitle(_translate("mainWindow", "Help", None))
        self.menuSettings.setTitle(_translate("mainWindow", "Settings", None))
        self.menuSave_2.setTitle(_translate("mainWindow", "Save", None))
        self.menuLoad_2.setTitle(_translate("mainWindow", "Load", None))
        self.controlsWidget.setWindowTitle(_translate("mainWindow", "Controls", None))
        self.stopButton.setText(_translate("mainWindow", "Stop", None))
        self.singleShotButton.setText(_translate("mainWindow", "Single shot", None))
        self.startButton.setText(_translate("mainWindow", "Start", None))
        self.frequenciesWidget.setWindowTitle(_translate("mainWindow", "Frequencies", None))
        self.pushButton.setText(_translate("mainWindow", "Add", None))
        self.label_2.setText(_translate("mainWindow", "Bin size", None))
        self.spinBox.setSuffix(_translate("mainWindow", " Hz", None))
        self.doubleSpinBox.setSuffix(_translate("mainWindow", " Hz", None))
        self.pushButton_2.setText(_translate("mainWindow", "Delete", None))
        self.label.setText(_translate("mainWindow", "Sample rate", None))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("mainWindow", "123123", None))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.actionWorkingFolder.setText(_translate("mainWindow", "WorkingFolder", None))
        self.actionExit.setText(_translate("mainWindow", "Exit", None))
        self.actionRestore_windows.setText(_translate("mainWindow", "Restore", None))
        self.actionAbout.setText(_translate("mainWindow", "About", None))
        self.actionFrequencySettings.setText(_translate("mainWindow", "FrequencySettings", None))
        self.actionAllSettings.setText(_translate("mainWindow", "AllSettings", None))
        self.actionFrequency_range.setText(_translate("mainWindow", "Frequency range", None))
        self.actionVoltage_range.setText(_translate("mainWindow", "Voltage range", None))
        self.actionAll.setText(_translate("mainWindow", "All", None))
        self.actionSaveAll.setText(_translate("mainWindow", "SaveAll", None))
        self.actionFrequencies.setText(_translate("mainWindow", "Frequencies", None))
        self.actionVoltages.setText(_translate("mainWindow", "Voltages", None))
        self.actionAll_2.setText(_translate("mainWindow", "All", None))
        self.actionFrequencies_2.setText(_translate("mainWindow", "Frequencies", None))
        self.actionVoltages_2.setText(_translate("mainWindow", "Voltages", None))
        self.actionAll_3.setText(_translate("mainWindow", "All", None))

from frequencywidget import FrequencyWidget
from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    mainWindow = QtGui.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())

