# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChannelSettings.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ChannelSettingsForm(object):
    def setupUi(self, ChannelSettingsForm):
        ChannelSettingsForm.setObjectName(_fromUtf8("ChannelSettingsForm"))
        ChannelSettingsForm.resize(188, 464)
        self.verticalLayout = QtGui.QVBoxLayout(ChannelSettingsForm)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(ChannelSettingsForm)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.AnalogInputRangeComboBox = QtGui.QComboBox(self.groupBox)
        self.AnalogInputRangeComboBox.setObjectName(_fromUtf8("AnalogInputRangeComboBox"))
        self.AnalogInputRangeComboBox.addItem(_fromUtf8(""))
        self.AnalogInputRangeComboBox.addItem(_fromUtf8(""))
        self.AnalogInputRangeComboBox.addItem(_fromUtf8(""))
        self.AnalogInputRangeComboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.AnalogInputRangeComboBox, 1, 1, 1, 1)
        self.UnipolarRadioButton = QtGui.QRadioButton(self.groupBox)
        self.UnipolarRadioButton.setObjectName(_fromUtf8("UnipolarRadioButton"))
        self.gridLayout.addWidget(self.UnipolarRadioButton, 2, 0, 1, 1)
        self.BipolarRadioButton = QtGui.QRadioButton(self.groupBox)
        self.BipolarRadioButton.setObjectName(_fromUtf8("BipolarRadioButton"))
        self.gridLayout.addWidget(self.BipolarRadioButton, 2, 1, 1, 1)
        self.AnaloInputChannelComboBox = QtGui.QComboBox(self.groupBox)
        self.AnaloInputChannelComboBox.setObjectName(_fromUtf8("AnaloInputChannelComboBox"))
        self.AnaloInputChannelComboBox.addItem(_fromUtf8(""))
        self.AnaloInputChannelComboBox.addItem(_fromUtf8(""))
        self.AnaloInputChannelComboBox.addItem(_fromUtf8(""))
        self.AnaloInputChannelComboBox.addItem(_fromUtf8(""))
        self.AnaloInputChannelComboBox.addItem(_fromUtf8(""))
        self.AnaloInputChannelComboBox.addItem(_fromUtf8(""))
        self.AnaloInputChannelComboBox.addItem(_fromUtf8(""))
        self.AnaloInputChannelComboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.AnaloInputChannelComboBox, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(ChannelSettingsForm)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.SampleVoltageMeasuremenChannelComboBox = QtGui.QComboBox(self.groupBox_2)
        self.SampleVoltageMeasuremenChannelComboBox.setObjectName(_fromUtf8("SampleVoltageMeasuremenChannelComboBox"))
        self.SampleVoltageMeasuremenChannelComboBox.addItem(_fromUtf8(""))
        self.SampleVoltageMeasuremenChannelComboBox.addItem(_fromUtf8(""))
        self.SampleVoltageMeasuremenChannelComboBox.addItem(_fromUtf8(""))
        self.SampleVoltageMeasuremenChannelComboBox.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.SampleVoltageMeasuremenChannelComboBox, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.GateVoltageMeasuremenChannelComboBox = QtGui.QComboBox(self.groupBox_2)
        self.GateVoltageMeasuremenChannelComboBox.setObjectName(_fromUtf8("GateVoltageMeasuremenChannelComboBox"))
        self.GateVoltageMeasuremenChannelComboBox.addItem(_fromUtf8(""))
        self.GateVoltageMeasuremenChannelComboBox.addItem(_fromUtf8(""))
        self.GateVoltageMeasuremenChannelComboBox.addItem(_fromUtf8(""))
        self.GateVoltageMeasuremenChannelComboBox.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.GateVoltageMeasuremenChannelComboBox, 1, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.MainVoltageMeasuremenChannelComboBox = QtGui.QComboBox(self.groupBox_2)
        self.MainVoltageMeasuremenChannelComboBox.setObjectName(_fromUtf8("MainVoltageMeasuremenChannelComboBox"))
        self.MainVoltageMeasuremenChannelComboBox.addItem(_fromUtf8(""))
        self.MainVoltageMeasuremenChannelComboBox.addItem(_fromUtf8(""))
        self.MainVoltageMeasuremenChannelComboBox.addItem(_fromUtf8(""))
        self.MainVoltageMeasuremenChannelComboBox.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.MainVoltageMeasuremenChannelComboBox, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(ChannelSettingsForm)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.SampleMotorComboBox = QtGui.QComboBox(self.groupBox_3)
        self.SampleMotorComboBox.setObjectName(_fromUtf8("SampleMotorComboBox"))
        self.SampleMotorComboBox.addItem(_fromUtf8(""))
        self.SampleMotorComboBox.addItem(_fromUtf8(""))
        self.SampleMotorComboBox.addItem(_fromUtf8(""))
        self.SampleMotorComboBox.addItem(_fromUtf8(""))
        self.SampleMotorComboBox.addItem(_fromUtf8(""))
        self.SampleMotorComboBox.addItem(_fromUtf8(""))
        self.SampleMotorComboBox.addItem(_fromUtf8(""))
        self.SampleMotorComboBox.addItem(_fromUtf8(""))
        self.SampleMotorComboBox.addItem(_fromUtf8(""))
        self.SampleMotorComboBox.addItem(_fromUtf8(""))
        self.SampleMotorComboBox.addItem(_fromUtf8(""))
        self.SampleMotorComboBox.addItem(_fromUtf8(""))
        self.SampleMotorComboBox.addItem(_fromUtf8(""))
        self.SampleMotorComboBox.addItem(_fromUtf8(""))
        self.SampleMotorComboBox.addItem(_fromUtf8(""))
        self.SampleMotorComboBox.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.SampleMotorComboBox, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.SampleRelayComboBox = QtGui.QComboBox(self.groupBox_3)
        self.SampleRelayComboBox.setObjectName(_fromUtf8("SampleRelayComboBox"))
        self.SampleRelayComboBox.addItem(_fromUtf8(""))
        self.SampleRelayComboBox.addItem(_fromUtf8(""))
        self.SampleRelayComboBox.addItem(_fromUtf8(""))
        self.SampleRelayComboBox.addItem(_fromUtf8(""))
        self.SampleRelayComboBox.addItem(_fromUtf8(""))
        self.SampleRelayComboBox.addItem(_fromUtf8(""))
        self.SampleRelayComboBox.addItem(_fromUtf8(""))
        self.SampleRelayComboBox.addItem(_fromUtf8(""))
        self.SampleRelayComboBox.addItem(_fromUtf8(""))
        self.SampleRelayComboBox.addItem(_fromUtf8(""))
        self.SampleRelayComboBox.addItem(_fromUtf8(""))
        self.SampleRelayComboBox.addItem(_fromUtf8(""))
        self.SampleRelayComboBox.addItem(_fromUtf8(""))
        self.SampleRelayComboBox.addItem(_fromUtf8(""))
        self.SampleRelayComboBox.addItem(_fromUtf8(""))
        self.SampleRelayComboBox.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.SampleRelayComboBox, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 2, 0, 1, 1)
        self.GatMotorComboBox = QtGui.QComboBox(self.groupBox_3)
        self.GatMotorComboBox.setObjectName(_fromUtf8("GatMotorComboBox"))
        self.GatMotorComboBox.addItem(_fromUtf8(""))
        self.GatMotorComboBox.addItem(_fromUtf8(""))
        self.GatMotorComboBox.addItem(_fromUtf8(""))
        self.GatMotorComboBox.addItem(_fromUtf8(""))
        self.GatMotorComboBox.addItem(_fromUtf8(""))
        self.GatMotorComboBox.addItem(_fromUtf8(""))
        self.GatMotorComboBox.addItem(_fromUtf8(""))
        self.GatMotorComboBox.addItem(_fromUtf8(""))
        self.GatMotorComboBox.addItem(_fromUtf8(""))
        self.GatMotorComboBox.addItem(_fromUtf8(""))
        self.GatMotorComboBox.addItem(_fromUtf8(""))
        self.GatMotorComboBox.addItem(_fromUtf8(""))
        self.GatMotorComboBox.addItem(_fromUtf8(""))
        self.GatMotorComboBox.addItem(_fromUtf8(""))
        self.GatMotorComboBox.addItem(_fromUtf8(""))
        self.GatMotorComboBox.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.GatMotorComboBox, 2, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 3, 0, 1, 1)
        self.GateRelayComboBox = QtGui.QComboBox(self.groupBox_3)
        self.GateRelayComboBox.setObjectName(_fromUtf8("GateRelayComboBox"))
        self.GateRelayComboBox.addItem(_fromUtf8(""))
        self.GateRelayComboBox.addItem(_fromUtf8(""))
        self.GateRelayComboBox.addItem(_fromUtf8(""))
        self.GateRelayComboBox.addItem(_fromUtf8(""))
        self.GateRelayComboBox.addItem(_fromUtf8(""))
        self.GateRelayComboBox.addItem(_fromUtf8(""))
        self.GateRelayComboBox.addItem(_fromUtf8(""))
        self.GateRelayComboBox.addItem(_fromUtf8(""))
        self.GateRelayComboBox.addItem(_fromUtf8(""))
        self.GateRelayComboBox.addItem(_fromUtf8(""))
        self.GateRelayComboBox.addItem(_fromUtf8(""))
        self.GateRelayComboBox.addItem(_fromUtf8(""))
        self.GateRelayComboBox.addItem(_fromUtf8(""))
        self.GateRelayComboBox.addItem(_fromUtf8(""))
        self.GateRelayComboBox.addItem(_fromUtf8(""))
        self.GateRelayComboBox.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.GateRelayComboBox, 3, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)

        self.retranslateUi(ChannelSettingsForm)
        self.SampleRelayComboBox.setCurrentIndex(1)
        self.GatMotorComboBox.setCurrentIndex(8)
        self.GateRelayComboBox.setCurrentIndex(9)
        QtCore.QMetaObject.connectSlotsByName(ChannelSettingsForm)

    def retranslateUi(self, ChannelSettingsForm):
        ChannelSettingsForm.setWindowTitle(_translate("ChannelSettingsForm", "Channel Settings", None))
        self.groupBox.setTitle(_translate("ChannelSettingsForm", "Analog Input Channel", None))
        self.label_2.setText(_translate("ChannelSettingsForm", "Range", None))
        self.AnalogInputRangeComboBox.setItemText(0, _translate("ChannelSettingsForm", "1.25", None))
        self.AnalogInputRangeComboBox.setItemText(1, _translate("ChannelSettingsForm", "2.5", None))
        self.AnalogInputRangeComboBox.setItemText(2, _translate("ChannelSettingsForm", "5", None))
        self.AnalogInputRangeComboBox.setItemText(3, _translate("ChannelSettingsForm", "10", None))
        self.UnipolarRadioButton.setText(_translate("ChannelSettingsForm", "Unipolar", None))
        self.BipolarRadioButton.setText(_translate("ChannelSettingsForm", "Bipolar", None))
        self.AnaloInputChannelComboBox.setItemText(0, _translate("ChannelSettingsForm", "In1", None))
        self.AnaloInputChannelComboBox.setItemText(1, _translate("ChannelSettingsForm", "In2", None))
        self.AnaloInputChannelComboBox.setItemText(2, _translate("ChannelSettingsForm", "In3", None))
        self.AnaloInputChannelComboBox.setItemText(3, _translate("ChannelSettingsForm", "In4", None))
        self.AnaloInputChannelComboBox.setItemText(4, _translate("ChannelSettingsForm", "In5", None))
        self.AnaloInputChannelComboBox.setItemText(5, _translate("ChannelSettingsForm", "In6", None))
        self.AnaloInputChannelComboBox.setItemText(6, _translate("ChannelSettingsForm", "In7", None))
        self.AnaloInputChannelComboBox.setItemText(7, _translate("ChannelSettingsForm", "In8", None))
        self.label.setText(_translate("ChannelSettingsForm", "Analog in", None))
        self.groupBox_2.setTitle(_translate("ChannelSettingsForm", "Voltage measurement Channels", None))
        self.label_3.setText(_translate("ChannelSettingsForm", "Sample Voltage", None))
        self.SampleVoltageMeasuremenChannelComboBox.setItemText(0, _translate("ChannelSettingsForm", "In5", None))
        self.SampleVoltageMeasuremenChannelComboBox.setItemText(1, _translate("ChannelSettingsForm", "In6", None))
        self.SampleVoltageMeasuremenChannelComboBox.setItemText(2, _translate("ChannelSettingsForm", "In7", None))
        self.SampleVoltageMeasuremenChannelComboBox.setItemText(3, _translate("ChannelSettingsForm", "In8", None))
        self.label_4.setText(_translate("ChannelSettingsForm", "Gate Voltage", None))
        self.GateVoltageMeasuremenChannelComboBox.setItemText(0, _translate("ChannelSettingsForm", "In5", None))
        self.GateVoltageMeasuremenChannelComboBox.setItemText(1, _translate("ChannelSettingsForm", "In6", None))
        self.GateVoltageMeasuremenChannelComboBox.setItemText(2, _translate("ChannelSettingsForm", "In7", None))
        self.GateVoltageMeasuremenChannelComboBox.setItemText(3, _translate("ChannelSettingsForm", "In8", None))
        self.label_9.setText(_translate("ChannelSettingsForm", "Main Voltage", None))
        self.MainVoltageMeasuremenChannelComboBox.setItemText(0, _translate("ChannelSettingsForm", "In5", None))
        self.MainVoltageMeasuremenChannelComboBox.setItemText(1, _translate("ChannelSettingsForm", "In6", None))
        self.MainVoltageMeasuremenChannelComboBox.setItemText(2, _translate("ChannelSettingsForm", "In7", None))
        self.MainVoltageMeasuremenChannelComboBox.setItemText(3, _translate("ChannelSettingsForm", "In8", None))
        self.groupBox_3.setTitle(_translate("ChannelSettingsForm", "Voltage setting", None))
        self.label_5.setText(_translate("ChannelSettingsForm", "Sample Motor", None))
        self.SampleMotorComboBox.setItemText(0, _translate("ChannelSettingsForm", "Out 1", None))
        self.SampleMotorComboBox.setItemText(1, _translate("ChannelSettingsForm", "Out 2", None))
        self.SampleMotorComboBox.setItemText(2, _translate("ChannelSettingsForm", "Out 3", None))
        self.SampleMotorComboBox.setItemText(3, _translate("ChannelSettingsForm", "Out 4", None))
        self.SampleMotorComboBox.setItemText(4, _translate("ChannelSettingsForm", "Out 5", None))
        self.SampleMotorComboBox.setItemText(5, _translate("ChannelSettingsForm", "Out 6", None))
        self.SampleMotorComboBox.setItemText(6, _translate("ChannelSettingsForm", "Out 7", None))
        self.SampleMotorComboBox.setItemText(7, _translate("ChannelSettingsForm", "Out 8", None))
        self.SampleMotorComboBox.setItemText(8, _translate("ChannelSettingsForm", "Out 9", None))
        self.SampleMotorComboBox.setItemText(9, _translate("ChannelSettingsForm", "Out 10", None))
        self.SampleMotorComboBox.setItemText(10, _translate("ChannelSettingsForm", "Out 11", None))
        self.SampleMotorComboBox.setItemText(11, _translate("ChannelSettingsForm", "Out 12", None))
        self.SampleMotorComboBox.setItemText(12, _translate("ChannelSettingsForm", "Out 13", None))
        self.SampleMotorComboBox.setItemText(13, _translate("ChannelSettingsForm", "Out 14", None))
        self.SampleMotorComboBox.setItemText(14, _translate("ChannelSettingsForm", "Out 15", None))
        self.SampleMotorComboBox.setItemText(15, _translate("ChannelSettingsForm", "Out 16", None))
        self.label_7.setText(_translate("ChannelSettingsForm", "Sample Relay", None))
        self.SampleRelayComboBox.setItemText(0, _translate("ChannelSettingsForm", "Out 1", None))
        self.SampleRelayComboBox.setItemText(1, _translate("ChannelSettingsForm", "Out 2", None))
        self.SampleRelayComboBox.setItemText(2, _translate("ChannelSettingsForm", "Out 3", None))
        self.SampleRelayComboBox.setItemText(3, _translate("ChannelSettingsForm", "Out 4", None))
        self.SampleRelayComboBox.setItemText(4, _translate("ChannelSettingsForm", "Out 5", None))
        self.SampleRelayComboBox.setItemText(5, _translate("ChannelSettingsForm", "Out 6", None))
        self.SampleRelayComboBox.setItemText(6, _translate("ChannelSettingsForm", "Out 7", None))
        self.SampleRelayComboBox.setItemText(7, _translate("ChannelSettingsForm", "Out 8", None))
        self.SampleRelayComboBox.setItemText(8, _translate("ChannelSettingsForm", "Out 9", None))
        self.SampleRelayComboBox.setItemText(9, _translate("ChannelSettingsForm", "Out 10", None))
        self.SampleRelayComboBox.setItemText(10, _translate("ChannelSettingsForm", "Out 11", None))
        self.SampleRelayComboBox.setItemText(11, _translate("ChannelSettingsForm", "Out 12", None))
        self.SampleRelayComboBox.setItemText(12, _translate("ChannelSettingsForm", "Out 13", None))
        self.SampleRelayComboBox.setItemText(13, _translate("ChannelSettingsForm", "Out 14", None))
        self.SampleRelayComboBox.setItemText(14, _translate("ChannelSettingsForm", "Out 15", None))
        self.SampleRelayComboBox.setItemText(15, _translate("ChannelSettingsForm", "Out 16", None))
        self.label_6.setText(_translate("ChannelSettingsForm", "Gate Motor", None))
        self.GatMotorComboBox.setItemText(0, _translate("ChannelSettingsForm", "Out 1", None))
        self.GatMotorComboBox.setItemText(1, _translate("ChannelSettingsForm", "Out 2", None))
        self.GatMotorComboBox.setItemText(2, _translate("ChannelSettingsForm", "Out 3", None))
        self.GatMotorComboBox.setItemText(3, _translate("ChannelSettingsForm", "Out 4", None))
        self.GatMotorComboBox.setItemText(4, _translate("ChannelSettingsForm", "Out 5", None))
        self.GatMotorComboBox.setItemText(5, _translate("ChannelSettingsForm", "Out 6", None))
        self.GatMotorComboBox.setItemText(6, _translate("ChannelSettingsForm", "Out 7", None))
        self.GatMotorComboBox.setItemText(7, _translate("ChannelSettingsForm", "Out 8", None))
        self.GatMotorComboBox.setItemText(8, _translate("ChannelSettingsForm", "Out 9", None))
        self.GatMotorComboBox.setItemText(9, _translate("ChannelSettingsForm", "Out 10", None))
        self.GatMotorComboBox.setItemText(10, _translate("ChannelSettingsForm", "Out 11", None))
        self.GatMotorComboBox.setItemText(11, _translate("ChannelSettingsForm", "Out 12", None))
        self.GatMotorComboBox.setItemText(12, _translate("ChannelSettingsForm", "Out 13", None))
        self.GatMotorComboBox.setItemText(13, _translate("ChannelSettingsForm", "Out 14", None))
        self.GatMotorComboBox.setItemText(14, _translate("ChannelSettingsForm", "Out 15", None))
        self.GatMotorComboBox.setItemText(15, _translate("ChannelSettingsForm", "Out 16", None))
        self.label_8.setText(_translate("ChannelSettingsForm", "Gate Relay", None))
        self.GateRelayComboBox.setItemText(0, _translate("ChannelSettingsForm", "Out 1", None))
        self.GateRelayComboBox.setItemText(1, _translate("ChannelSettingsForm", "Out 2", None))
        self.GateRelayComboBox.setItemText(2, _translate("ChannelSettingsForm", "Out 3", None))
        self.GateRelayComboBox.setItemText(3, _translate("ChannelSettingsForm", "Out 4", None))
        self.GateRelayComboBox.setItemText(4, _translate("ChannelSettingsForm", "Out 5", None))
        self.GateRelayComboBox.setItemText(5, _translate("ChannelSettingsForm", "Out 6", None))
        self.GateRelayComboBox.setItemText(6, _translate("ChannelSettingsForm", "Out 7", None))
        self.GateRelayComboBox.setItemText(7, _translate("ChannelSettingsForm", "Out 8", None))
        self.GateRelayComboBox.setItemText(8, _translate("ChannelSettingsForm", "Out 9", None))
        self.GateRelayComboBox.setItemText(9, _translate("ChannelSettingsForm", "Out 10", None))
        self.GateRelayComboBox.setItemText(10, _translate("ChannelSettingsForm", "Out 11", None))
        self.GateRelayComboBox.setItemText(11, _translate("ChannelSettingsForm", "Out 12", None))
        self.GateRelayComboBox.setItemText(12, _translate("ChannelSettingsForm", "Out 13", None))
        self.GateRelayComboBox.setItemText(13, _translate("ChannelSettingsForm", "Out 14", None))
        self.GateRelayComboBox.setItemText(14, _translate("ChannelSettingsForm", "Out 15", None))
        self.GateRelayComboBox.setItemText(15, _translate("ChannelSettingsForm", "Out 16", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    ChannelSettingsForm = QtGui.QWidget()
    ui = Ui_ChannelSettingsForm()
    ui.setupUi(ChannelSettingsForm)
    ChannelSettingsForm.show()
    sys.exit(app.exec_())

