# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Programming\Repositories\PyFANS\PyFANS\UI\UI_RangeSelector_v6.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_RangeSelector(object):
    def setupUi(self, RangeSelector):
        RangeSelector.setObjectName(_fromUtf8("RangeSelector"))
        RangeSelector.resize(400, 933)
        self.verticalLayout_3 = QtGui.QVBoxLayout(RangeSelector)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.ui_composed_handler = QtGui.QRadioButton(RangeSelector)
        self.ui_composed_handler.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_composed_handler.sizePolicy().hasHeightForWidth())
        self.ui_composed_handler.setSizePolicy(sizePolicy)
        self.ui_composed_handler.setObjectName(_fromUtf8("ui_composed_handler"))
        self.gridLayout.addWidget(self.ui_composed_handler, 0, 1, 1, 1)
        self.ui_normal_handler = QtGui.QRadioButton(RangeSelector)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_normal_handler.sizePolicy().hasHeightForWidth())
        self.ui_normal_handler.setSizePolicy(sizePolicy)
        self.ui_normal_handler.setObjectName(_fromUtf8("ui_normal_handler"))
        self.gridLayout.addWidget(self.ui_normal_handler, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.ui_composite_ranges = QtGui.QFrame(RangeSelector)
        self.ui_composite_ranges.setFrameShape(QtGui.QFrame.StyledPanel)
        self.ui_composite_ranges.setFrameShadow(QtGui.QFrame.Raised)
        self.ui_composite_ranges.setObjectName(_fromUtf8("ui_composite_ranges"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.ui_composite_ranges)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.listView = QtGui.QListView(self.ui_composite_ranges)
        self.listView.setObjectName(_fromUtf8("listView"))
        self.horizontalLayout.addWidget(self.listView)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.pushButton = QtGui.QPushButton(self.ui_composite_ranges)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.ui_composite_ranges)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.verticalLayout_2.addWidget(self.pushButton_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addWidget(self.ui_composite_ranges)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.ui_handler_selector = QtGui.QComboBox(RangeSelector)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_handler_selector.sizePolicy().hasHeightForWidth())
        self.ui_handler_selector.setSizePolicy(sizePolicy)
        self.ui_handler_selector.setObjectName(_fromUtf8("ui_handler_selector"))
        self.ui_handler_selector.addItem(_fromUtf8(""))
        self.ui_handler_selector.addItem(_fromUtf8(""))
        self.ui_handler_selector.addItem(_fromUtf8(""))
        self.ui_handler_selector.addItem(_fromUtf8(""))
        self.ui_handler_selector.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.ui_handler_selector)
        self.ui_span_mode = QtGui.QCheckBox(RangeSelector)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_span_mode.sizePolicy().hasHeightForWidth())
        self.ui_span_mode.setSizePolicy(sizePolicy)
        self.ui_span_mode.setObjectName(_fromUtf8("ui_span_mode"))
        self.horizontalLayout_2.addWidget(self.ui_span_mode)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.ui_range_info_area = QtGui.QGroupBox(RangeSelector)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_range_info_area.sizePolicy().hasHeightForWidth())
        self.ui_range_info_area.setSizePolicy(sizePolicy)
        self.ui_range_info_area.setObjectName(_fromUtf8("ui_range_info_area"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.ui_range_info_area)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.ui_normal_range_info = QtGui.QFrame(self.ui_range_info_area)
        self.ui_normal_range_info.setFrameShape(QtGui.QFrame.StyledPanel)
        self.ui_normal_range_info.setFrameShadow(QtGui.QFrame.Raised)
        self.ui_normal_range_info.setObjectName(_fromUtf8("ui_normal_range_info"))
        self.gridLayout_3 = QtGui.QGridLayout(self.ui_normal_range_info)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.ui_center_label = QtGui.QLabel(self.ui_normal_range_info)
        self.ui_center_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ui_center_label.setObjectName(_fromUtf8("ui_center_label"))
        self.gridLayout_3.addWidget(self.ui_center_label, 0, 0, 1, 1)
        self.ui_center_val = QtGui.QLineEdit(self.ui_normal_range_info)
        self.ui_center_val.setObjectName(_fromUtf8("ui_center_val"))
        self.gridLayout_3.addWidget(self.ui_center_val, 0, 1, 1, 1)
        self.ui_span_label = QtGui.QLabel(self.ui_normal_range_info)
        self.ui_span_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ui_span_label.setObjectName(_fromUtf8("ui_span_label"))
        self.gridLayout_3.addWidget(self.ui_span_label, 1, 0, 1, 1)
        self.ui_span_val = QtGui.QLineEdit(self.ui_normal_range_info)
        self.ui_span_val.setObjectName(_fromUtf8("ui_span_val"))
        self.gridLayout_3.addWidget(self.ui_span_val, 1, 1, 1, 1)
        self.ui_start_label = QtGui.QLabel(self.ui_normal_range_info)
        self.ui_start_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ui_start_label.setObjectName(_fromUtf8("ui_start_label"))
        self.gridLayout_3.addWidget(self.ui_start_label, 2, 0, 1, 1)
        self.ui_start_val = QtGui.QLineEdit(self.ui_normal_range_info)
        self.ui_start_val.setObjectName(_fromUtf8("ui_start_val"))
        self.gridLayout_3.addWidget(self.ui_start_val, 2, 1, 1, 1)
        self.ui_stop_label = QtGui.QLabel(self.ui_normal_range_info)
        self.ui_stop_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ui_stop_label.setObjectName(_fromUtf8("ui_stop_label"))
        self.gridLayout_3.addWidget(self.ui_stop_label, 3, 0, 1, 1)
        self.ui_stop_val = QtGui.QLineEdit(self.ui_normal_range_info)
        self.ui_stop_val.setObjectName(_fromUtf8("ui_stop_val"))
        self.gridLayout_3.addWidget(self.ui_stop_val, 3, 1, 1, 1)
        self.ui_step_label = QtGui.QLabel(self.ui_normal_range_info)
        self.ui_step_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ui_step_label.setObjectName(_fromUtf8("ui_step_label"))
        self.gridLayout_3.addWidget(self.ui_step_label, 4, 0, 1, 1)
        self.ui_step_val = QtGui.QLineEdit(self.ui_normal_range_info)
        self.ui_step_val.setReadOnly(False)
        self.ui_step_val.setObjectName(_fromUtf8("ui_step_val"))
        self.gridLayout_3.addWidget(self.ui_step_val, 4, 1, 1, 1)
        self.ui_start_label.raise_()
        self.ui_start_val.raise_()
        self.ui_stop_label.raise_()
        self.ui_stop_val.raise_()
        self.ui_step_label.raise_()
        self.ui_step_val.raise_()
        self.ui_span_val.raise_()
        self.ui_span_label.raise_()
        self.ui_center_val.raise_()
        self.ui_center_label.raise_()
        self.verticalLayout_4.addWidget(self.ui_normal_range_info)
        self.ui_custom_list_view = QtGui.QFrame(self.ui_range_info_area)
        self.ui_custom_list_view.setFrameShape(QtGui.QFrame.StyledPanel)
        self.ui_custom_list_view.setFrameShadow(QtGui.QFrame.Raised)
        self.ui_custom_list_view.setObjectName(_fromUtf8("ui_custom_list_view"))
        self.verticalLayout = QtGui.QVBoxLayout(self.ui_custom_list_view)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.ui_list_of_values = QtGui.QListWidget(self.ui_custom_list_view)
        self.ui_list_of_values.setObjectName(_fromUtf8("ui_list_of_values"))
        self.verticalLayout.addWidget(self.ui_list_of_values)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.ui_custom_value_to_add = QtGui.QLineEdit(self.ui_custom_list_view)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_custom_value_to_add.sizePolicy().hasHeightForWidth())
        self.ui_custom_value_to_add.setSizePolicy(sizePolicy)
        self.ui_custom_value_to_add.setObjectName(_fromUtf8("ui_custom_value_to_add"))
        self.horizontalLayout_3.addWidget(self.ui_custom_value_to_add)
        self.ui_add_custom_value = QtGui.QPushButton(self.ui_custom_list_view)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_add_custom_value.sizePolicy().hasHeightForWidth())
        self.ui_add_custom_value.setSizePolicy(sizePolicy)
        self.ui_add_custom_value.setMaximumSize(QtCore.QSize(20, 16777215))
        self.ui_add_custom_value.setObjectName(_fromUtf8("ui_add_custom_value"))
        self.horizontalLayout_3.addWidget(self.ui_add_custom_value)
        self.ui_add_range_button = QtGui.QPushButton(self.ui_custom_list_view)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_add_range_button.sizePolicy().hasHeightForWidth())
        self.ui_add_range_button.setSizePolicy(sizePolicy)
        self.ui_add_range_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ui_add_range_button.setObjectName(_fromUtf8("ui_add_range_button"))
        self.horizontalLayout_3.addWidget(self.ui_add_range_button)
        self.ui_remove_custom_value = QtGui.QPushButton(self.ui_custom_list_view)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_remove_custom_value.sizePolicy().hasHeightForWidth())
        self.ui_remove_custom_value.setSizePolicy(sizePolicy)
        self.ui_remove_custom_value.setMaximumSize(QtCore.QSize(20, 16777215))
        self.ui_remove_custom_value.setObjectName(_fromUtf8("ui_remove_custom_value"))
        self.horizontalLayout_3.addWidget(self.ui_remove_custom_value)
        self.ui_clear_custom_value = QtGui.QPushButton(self.ui_custom_list_view)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_clear_custom_value.sizePolicy().hasHeightForWidth())
        self.ui_clear_custom_value.setSizePolicy(sizePolicy)
        self.ui_clear_custom_value.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ui_clear_custom_value.setObjectName(_fromUtf8("ui_clear_custom_value"))
        self.horizontalLayout_3.addWidget(self.ui_clear_custom_value)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addWidget(self.ui_custom_list_view)
        self.verticalLayout_3.addWidget(self.ui_range_info_area)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(RangeSelector)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.ui_range_repeats = QtGui.QSpinBox(RangeSelector)
        self.ui_range_repeats.setMinimum(1)
        self.ui_range_repeats.setMaximum(999999999)
        self.ui_range_repeats.setObjectName(_fromUtf8("ui_range_repeats"))
        self.gridLayout_2.addWidget(self.ui_range_repeats, 0, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.ui_view_range_dock = QtGui.QDockWidget(RangeSelector)
        self.ui_view_range_dock.setObjectName(_fromUtf8("ui_view_range_dock"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_5.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.ui_range_plot = GraphicsLayoutWidget(self.dockWidgetContents)
        self.ui_range_plot.setObjectName(_fromUtf8("ui_range_plot"))
        self.verticalLayout_5.addWidget(self.ui_range_plot)
        self.ui_view_range_dock.setWidget(self.dockWidgetContents)
        self.verticalLayout_3.addWidget(self.ui_view_range_dock)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.ui_view_range = QtGui.QPushButton(RangeSelector)
        self.ui_view_range.setObjectName(_fromUtf8("ui_view_range"))
        self.gridLayout_4.addWidget(self.ui_view_range, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 1, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(RangeSelector)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_4.addWidget(self.buttonBox, 0, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_4)

        self.retranslateUi(RangeSelector)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), RangeSelector.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), RangeSelector.reject)
        QtCore.QMetaObject.connectSlotsByName(RangeSelector)

    def retranslateUi(self, RangeSelector):
        RangeSelector.setWindowTitle(_translate("RangeSelector", "Range Editor", None))
        self.ui_composed_handler.setText(_translate("RangeSelector", "Composed", None))
        self.ui_normal_handler.setText(_translate("RangeSelector", "Normal", None))
        self.pushButton.setText(_translate("RangeSelector", "Add", None))
        self.pushButton_2.setText(_translate("RangeSelector", "Remove", None))
        self.ui_handler_selector.setItemText(0, _translate("RangeSelector", "Normal", None))
        self.ui_handler_selector.setItemText(1, _translate("RangeSelector", "Back and forth", None))
        self.ui_handler_selector.setItemText(2, _translate("RangeSelector", "Centered ", None))
        self.ui_handler_selector.setItemText(3, _translate("RangeSelector", "Centered back and forth", None))
        self.ui_handler_selector.setItemText(4, _translate("RangeSelector", "Custom list", None))
        self.ui_span_mode.setText(_translate("RangeSelector", "Span", None))
        self.ui_range_info_area.setTitle(_translate("RangeSelector", "Range Info", None))
        self.ui_center_label.setText(_translate("RangeSelector", "Center", None))
        self.ui_center_val.setPlaceholderText(_translate("RangeSelector", "center", None))
        self.ui_span_label.setText(_translate("RangeSelector", "Span", None))
        self.ui_span_val.setPlaceholderText(_translate("RangeSelector", "span", None))
        self.ui_start_label.setText(_translate("RangeSelector", "Start", None))
        self.ui_start_val.setPlaceholderText(_translate("RangeSelector", "start", None))
        self.ui_stop_label.setText(_translate("RangeSelector", "Stop", None))
        self.ui_stop_val.setPlaceholderText(_translate("RangeSelector", "stop", None))
        self.ui_step_label.setText(_translate("RangeSelector", "Step", None))
        self.ui_step_val.setPlaceholderText(_translate("RangeSelector", "step", None))
        self.ui_add_custom_value.setText(_translate("RangeSelector", "+", None))
        self.ui_add_range_button.setText(_translate("RangeSelector", "+ range", None))
        self.ui_remove_custom_value.setText(_translate("RangeSelector", "-", None))
        self.ui_clear_custom_value.setText(_translate("RangeSelector", "Clear", None))
        self.label.setText(_translate("RangeSelector", "Repeats", None))
        self.ui_view_range_dock.setWindowTitle(_translate("RangeSelector", "Range visualization", None))
        self.ui_view_range.setText(_translate("RangeSelector", "View", None))

from pyqtgraph import GraphicsLayoutWidget
