# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Programming\Repositories\PyFANS\PyFANS\UI\UI_Analyzer.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Analyzer(object):
    def setupUi(self, Analyzer):
        Analyzer.setObjectName(_fromUtf8("Analyzer"))
        Analyzer.resize(1048, 975)
        self.centralwidget = QtGui.QWidget(Analyzer)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.ui_plot = GraphicsLayoutWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_plot.sizePolicy().hasHeightForWidth())
        self.ui_plot.setSizePolicy(sizePolicy)
        self.ui_plot.setObjectName(_fromUtf8("ui_plot"))
        self.horizontalLayout_3.addWidget(self.ui_plot)
        self.frame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.groupBox_4 = QtGui.QGroupBox(self.frame)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.ui_cutoff_correction_enabled = QtGui.QCheckBox(self.groupBox_4)
        self.ui_cutoff_correction_enabled.setObjectName(_fromUtf8("ui_cutoff_correction_enabled"))
        self.gridLayout.addWidget(self.ui_cutoff_correction_enabled, 2, 0, 1, 1)
        self.ui_cutoff_correction_capacity = QtGui.QLineEdit(self.groupBox_4)
        self.ui_cutoff_correction_capacity.setObjectName(_fromUtf8("ui_cutoff_correction_capacity"))
        self.gridLayout.addWidget(self.ui_cutoff_correction_capacity, 2, 2, 1, 1)
        self.ui_smoothing_enabled = QtGui.QCheckBox(self.groupBox_4)
        self.ui_smoothing_enabled.setObjectName(_fromUtf8("ui_smoothing_enabled"))
        self.gridLayout.addWidget(self.ui_smoothing_enabled, 1, 0, 1, 1)
        self.ui_smoothing_winsize = QtGui.QSpinBox(self.groupBox_4)
        self.ui_smoothing_winsize.setMaximum(99999)
        self.ui_smoothing_winsize.setObjectName(_fromUtf8("ui_smoothing_winsize"))
        self.gridLayout.addWidget(self.ui_smoothing_winsize, 1, 2, 1, 1)
        self.ui_remove_pickups_enabled = QtGui.QCheckBox(self.groupBox_4)
        self.ui_remove_pickups_enabled.setObjectName(_fromUtf8("ui_remove_pickups_enabled"))
        self.gridLayout.addWidget(self.ui_remove_pickups_enabled, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 1, 1, 1)
        self.ui_multiply_by_frequency = QtGui.QCheckBox(self.groupBox_4)
        self.ui_multiply_by_frequency.setObjectName(_fromUtf8("ui_multiply_by_frequency"))
        self.gridLayout.addWidget(self.ui_multiply_by_frequency, 3, 0, 1, 3)
        self.ui_hide_original = QtGui.QCheckBox(self.groupBox_4)
        self.ui_hide_original.setObjectName(_fromUtf8("ui_hide_original"))
        self.gridLayout.addWidget(self.ui_hide_original, 0, 2, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.ui_crop_start_frequency = QtGui.QLineEdit(self.groupBox_4)
        self.ui_crop_start_frequency.setObjectName(_fromUtf8("ui_crop_start_frequency"))
        self.horizontalLayout_4.addWidget(self.ui_crop_start_frequency)
        self.ui_crop_stop_frequency = QtGui.QLineEdit(self.groupBox_4)
        self.ui_crop_stop_frequency.setObjectName(_fromUtf8("ui_crop_stop_frequency"))
        self.horizontalLayout_4.addWidget(self.ui_crop_stop_frequency)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.ui_crop_button = QtGui.QPushButton(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_crop_button.sizePolicy().hasHeightForWidth())
        self.ui_crop_button.setSizePolicy(sizePolicy)
        self.ui_crop_button.setObjectName(_fromUtf8("ui_crop_button"))
        self.horizontalLayout.addWidget(self.ui_crop_button)
        self.ui_crop_undo_button = QtGui.QPushButton(self.groupBox_4)
        self.ui_crop_undo_button.setObjectName(_fromUtf8("ui_crop_undo_button"))
        self.horizontalLayout.addWidget(self.ui_crop_undo_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_10.addLayout(self.verticalLayout)
        self.verticalLayout_8.addWidget(self.groupBox_4)
        self.ui_thermal_groupbox = QtGui.QGroupBox(self.frame)
        self.ui_thermal_groupbox.setFlat(False)
        self.ui_thermal_groupbox.setCheckable(True)
        self.ui_thermal_groupbox.setObjectName(_fromUtf8("ui_thermal_groupbox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.ui_thermal_groupbox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label = QtGui.QLabel(self.ui_thermal_groupbox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.ui_equivalent_resistance = QtGui.QLineEdit(self.ui_thermal_groupbox)
        self.ui_equivalent_resistance.setReadOnly(False)
        self.ui_equivalent_resistance.setObjectName(_fromUtf8("ui_equivalent_resistance"))
        self.gridLayout_3.addWidget(self.ui_equivalent_resistance, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.ui_thermal_groupbox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.ui_temperature = QtGui.QLineEdit(self.ui_thermal_groupbox)
        self.ui_temperature.setReadOnly(False)
        self.ui_temperature.setObjectName(_fromUtf8("ui_temperature"))
        self.gridLayout_3.addWidget(self.ui_temperature, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.ui_subtract_thermal_noise = QtGui.QCheckBox(self.ui_thermal_groupbox)
        self.ui_subtract_thermal_noise.setObjectName(_fromUtf8("ui_subtract_thermal_noise"))
        self.verticalLayout_2.addWidget(self.ui_subtract_thermal_noise)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_8.addWidget(self.ui_thermal_groupbox)
        self.ui_flicker_groupbox = QtGui.QGroupBox(self.frame)
        self.ui_flicker_groupbox.setCheckable(True)
        self.ui_flicker_groupbox.setObjectName(_fromUtf8("ui_flicker_groupbox"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.ui_flicker_groupbox)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_5 = QtGui.QLabel(self.ui_flicker_groupbox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.ui_flicker_amplitude = QtGui.QLineEdit(self.ui_flicker_groupbox)
        self.ui_flicker_amplitude.setObjectName(_fromUtf8("ui_flicker_amplitude"))
        self.gridLayout_2.addWidget(self.ui_flicker_amplitude, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.ui_flicker_groupbox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.ui_flicker_alpha = QtGui.QLineEdit(self.ui_flicker_groupbox)
        self.ui_flicker_alpha.setObjectName(_fromUtf8("ui_flicker_alpha"))
        self.gridLayout_2.addWidget(self.ui_flicker_alpha, 2, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.ui_flicker_groupbox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.ui_flicker_frequency = QtGui.QLineEdit(self.ui_flicker_groupbox)
        self.ui_flicker_frequency.setObjectName(_fromUtf8("ui_flicker_frequency"))
        self.gridLayout_2.addWidget(self.ui_flicker_frequency, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.ui_flicker_noise_reset_button = QtGui.QPushButton(self.ui_flicker_groupbox)
        self.ui_flicker_noise_reset_button.setObjectName(_fromUtf8("ui_flicker_noise_reset_button"))
        self.verticalLayout_4.addWidget(self.ui_flicker_noise_reset_button)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_8.addWidget(self.ui_flicker_groupbox)
        self.ui_gr_groupbox = QtGui.QGroupBox(self.frame)
        self.ui_gr_groupbox.setCheckable(False)
        self.ui_gr_groupbox.setObjectName(_fromUtf8("ui_gr_groupbox"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.ui_gr_groupbox)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.ui_gr_amplitude = QtGui.QLineEdit(self.ui_gr_groupbox)
        self.ui_gr_amplitude.setObjectName(_fromUtf8("ui_gr_amplitude"))
        self.gridLayout_4.addWidget(self.ui_gr_amplitude, 2, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.ui_gr_groupbox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 1, 0, 1, 1)
        self.ui_gr_frequency = QtGui.QLineEdit(self.ui_gr_groupbox)
        self.ui_gr_frequency.setObjectName(_fromUtf8("ui_gr_frequency"))
        self.gridLayout_4.addWidget(self.ui_gr_frequency, 1, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.ui_gr_groupbox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 2, 0, 1, 1)
        self.ui_gr_enabled = QtGui.QCheckBox(self.ui_gr_groupbox)
        self.ui_gr_enabled.setObjectName(_fromUtf8("ui_gr_enabled"))
        self.gridLayout_4.addWidget(self.ui_gr_enabled, 0, 0, 1, 2)
        self.verticalLayout_7.addLayout(self.gridLayout_4)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.ui_gr_listview = QtGui.QListWidget(self.ui_gr_groupbox)
        self.ui_gr_listview.setObjectName(_fromUtf8("ui_gr_listview"))
        self.verticalLayout_6.addWidget(self.ui_gr_listview)
        self.ui_gr_properties_layout = QtGui.QVBoxLayout()
        self.ui_gr_properties_layout.setObjectName(_fromUtf8("ui_gr_properties_layout"))
        self.verticalLayout_6.addLayout(self.ui_gr_properties_layout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.ui_add_gr_noise_button = QtGui.QPushButton(self.ui_gr_groupbox)
        self.ui_add_gr_noise_button.setObjectName(_fromUtf8("ui_add_gr_noise_button"))
        self.horizontalLayout_2.addWidget(self.ui_add_gr_noise_button)
        self.ui_remove_gr_noise_button = QtGui.QPushButton(self.ui_gr_groupbox)
        self.ui_remove_gr_noise_button.setObjectName(_fromUtf8("ui_remove_gr_noise_button"))
        self.horizontalLayout_2.addWidget(self.ui_remove_gr_noise_button)
        self.ui_reset_gr_noise_button = QtGui.QPushButton(self.ui_gr_groupbox)
        self.ui_reset_gr_noise_button.setObjectName(_fromUtf8("ui_reset_gr_noise_button"))
        self.horizontalLayout_2.addWidget(self.ui_reset_gr_noise_button)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_8.addWidget(self.ui_gr_groupbox)
        self.ui_autofit = QtGui.QCheckBox(self.frame)
        self.ui_autofit.setObjectName(_fromUtf8("ui_autofit"))
        self.verticalLayout_8.addWidget(self.ui_autofit)
        self.ui_fit_data_button = QtGui.QPushButton(self.frame)
        self.ui_fit_data_button.setObjectName(_fromUtf8("ui_fit_data_button"))
        self.verticalLayout_8.addWidget(self.ui_fit_data_button)
        spacerItem = QtGui.QSpacerItem(20, 107, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem)
        self.horizontalLayout_3.addWidget(self.frame)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        Analyzer.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Analyzer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1048, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        Analyzer.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Analyzer)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Analyzer.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(Analyzer)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        Analyzer.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen_File = QtGui.QAction(Analyzer)
        self.actionOpen_File.setObjectName(_fromUtf8("actionOpen_File"))
        self.actionOpen_Folder = QtGui.QAction(Analyzer)
        self.actionOpen_Folder.setObjectName(_fromUtf8("actionOpen_Folder"))
        self.actionSave = QtGui.QAction(Analyzer)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionFlicker = QtGui.QAction(Analyzer)
        self.actionFlicker.setObjectName(_fromUtf8("actionFlicker"))
        self.actionGR = QtGui.QAction(Analyzer)
        self.actionGR.setObjectName(_fromUtf8("actionGR"))
        self.actionNext = QtGui.QAction(Analyzer)
        self.actionNext.setObjectName(_fromUtf8("actionNext"))
        self.actionPrev = QtGui.QAction(Analyzer)
        self.actionPrev.setObjectName(_fromUtf8("actionPrev"))
        self.actionShowSettingsTree = QtGui.QAction(Analyzer)
        self.actionShowSettingsTree.setObjectName(_fromUtf8("actionShowSettingsTree"))
        self.actionTest = QtGui.QAction(Analyzer)
        self.actionTest.setObjectName(_fromUtf8("actionTest"))
        self.action_export = QtGui.QAction(Analyzer)
        self.action_export.setObjectName(_fromUtf8("action_export"))
        self.action_open_working_folder = QtGui.QAction(Analyzer)
        self.action_open_working_folder.setObjectName(_fromUtf8("action_open_working_folder"))
        self.action_open_plotter = QtGui.QAction(Analyzer)
        self.action_open_plotter.setObjectName(_fromUtf8("action_open_plotter"))
        self.menuFile.addAction(self.actionOpen_File)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.action_export)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_open_working_folder)
        self.menuView.addAction(self.action_open_plotter)
        self.menuView.addAction(self.actionShowSettingsTree)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.toolBar.addAction(self.actionOpen_File)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.action_export)
        self.toolBar.addAction(self.actionPrev)
        self.toolBar.addAction(self.actionNext)

        self.retranslateUi(Analyzer)
        QtCore.QMetaObject.connectSlotsByName(Analyzer)

    def retranslateUi(self, Analyzer):
        Analyzer.setWindowTitle(_translate("Analyzer", "PyFANS Analyzer", None))
        self.groupBox_4.setTitle(_translate("Analyzer", "Correction", None))
        self.ui_cutoff_correction_enabled.setText(_translate("Analyzer", "Cutoff correction", None))
        self.ui_smoothing_enabled.setText(_translate("Analyzer", "Smoothing", None))
        self.ui_remove_pickups_enabled.setText(_translate("Analyzer", "Remove 50 Hz", None))
        self.label_3.setText(_translate("Analyzer", "#", None))
        self.label_4.setText(_translate("Analyzer", "C", None))
        self.ui_multiply_by_frequency.setText(_translate("Analyzer", "Multiply by frequency", None))
        self.ui_hide_original.setText(_translate("Analyzer", "Hide original", None))
        self.ui_crop_start_frequency.setPlaceholderText(_translate("Analyzer", "start frequency", None))
        self.ui_crop_stop_frequency.setPlaceholderText(_translate("Analyzer", "stop_frequency", None))
        self.ui_crop_button.setText(_translate("Analyzer", "Crop", None))
        self.ui_crop_undo_button.setText(_translate("Analyzer", "Undo", None))
        self.ui_thermal_groupbox.setTitle(_translate("Analyzer", "Thermal Noise", None))
        self.label.setText(_translate("Analyzer", "Equivalent Resistance", None))
        self.label_7.setText(_translate("Analyzer", "Temperature", None))
        self.ui_subtract_thermal_noise.setText(_translate("Analyzer", "Subtract Thermal Noise", None))
        self.ui_flicker_groupbox.setTitle(_translate("Analyzer", "Flicker Noise", None))
        self.label_5.setText(_translate("Analyzer", "Noise Amplitude", None))
        self.label_6.setText(_translate("Analyzer", "Power", None))
        self.label_2.setText(_translate("Analyzer", "Frequency", None))
        self.ui_flicker_noise_reset_button.setText(_translate("Analyzer", "Reset", None))
        self.ui_gr_groupbox.setTitle(_translate("Analyzer", "GR Noise", None))
        self.label_8.setText(_translate("Analyzer", "Frequency", None))
        self.label_9.setText(_translate("Analyzer", "Amplitude", None))
        self.ui_gr_enabled.setText(_translate("Analyzer", "Enable", None))
        self.ui_add_gr_noise_button.setText(_translate("Analyzer", "Add", None))
        self.ui_remove_gr_noise_button.setText(_translate("Analyzer", "Remove", None))
        self.ui_reset_gr_noise_button.setText(_translate("Analyzer", "Reset", None))
        self.ui_autofit.setText(_translate("Analyzer", "AutoFit", None))
        self.ui_fit_data_button.setText(_translate("Analyzer", "Fit noise model to data", None))
        self.menuFile.setTitle(_translate("Analyzer", "File", None))
        self.menuView.setTitle(_translate("Analyzer", "View", None))
        self.toolBar.setWindowTitle(_translate("Analyzer", "toolBar", None))
        self.actionOpen_File.setText(_translate("Analyzer", "Open", None))
        self.actionOpen_Folder.setText(_translate("Analyzer", "Open Folder", None))
        self.actionSave.setText(_translate("Analyzer", "Save", None))
        self.actionFlicker.setText(_translate("Analyzer", "Flicker", None))
        self.actionFlicker.setToolTip(_translate("Analyzer", "Flicker noise handle", None))
        self.actionGR.setText(_translate("Analyzer", "GR", None))
        self.actionGR.setToolTip(_translate("Analyzer", "Lorentzian-shape noise handle", None))
        self.actionNext.setText(_translate("Analyzer", "Next", None))
        self.actionNext.setShortcut(_translate("Analyzer", "Ctrl+Right", None))
        self.actionPrev.setText(_translate("Analyzer", "Prev", None))
        self.actionPrev.setShortcut(_translate("Analyzer", "Ctrl+Left", None))
        self.actionShowSettingsTree.setText(_translate("Analyzer", "Settings", None))
        self.actionTest.setText(_translate("Analyzer", "test", None))
        self.action_export.setText(_translate("Analyzer", "Export", None))
        self.action_open_working_folder.setText(_translate("Analyzer", "Open Folder", None))
        self.action_open_plotter.setText(_translate("Analyzer", "Open Plotter", None))

from pyqtgraph import GraphicsLayoutWidget
