# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainform.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName(_fromUtf8("mainWindow"))
        mainWindow.resize(856, 716)
        mainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.plotSplitter = QtGui.QSplitter(self.centralwidget)
        self.plotSplitter.setOrientation(QtCore.Qt.Vertical)
        self.plotSplitter.setObjectName(_fromUtf8("plotSplitter"))
        self.timetracePlot = GraphicsLayoutWidget(self.plotSplitter)
        self.timetracePlot.setMinimumSize(QtCore.QSize(10, 10))
        self.timetracePlot.setObjectName(_fromUtf8("timetracePlot"))
        self.noisePlot = GraphicsLayoutWidget(self.plotSplitter)
        self.noisePlot.setObjectName(_fromUtf8("noisePlot"))
        self.verticalLayout.addWidget(self.plotSplitter)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 856, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuWindow = QtGui.QMenu(self.menubar)
        self.menuWindow.setObjectName(_fromUtf8("menuWindow"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuSave_2 = QtGui.QMenu(self.menuSettings)
        self.menuSave_2.setObjectName(_fromUtf8("menuSave_2"))
        self.menuLoad_2 = QtGui.QMenu(self.menuSettings)
        self.menuLoad_2.setObjectName(_fromUtf8("menuLoad_2"))
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(mainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        mainWindow.setStatusBar(self.statusbar)
        self.controlsWidget = QtGui.QDockWidget(mainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlsWidget.sizePolicy().hasHeightForWidth())
        self.controlsWidget.setSizePolicy(sizePolicy)
        self.controlsWidget.setMinimumSize(QtCore.QSize(195, 91))
        self.controlsWidget.setMaximumSize(QtCore.QSize(200, 100))
        self.controlsWidget.setAcceptDrops(False)
        self.controlsWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.controlsWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.controlsWidget.setObjectName(_fromUtf8("controlsWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setEnabled(True)
        self.dockWidgetContents.setBaseSize(QtCore.QSize(0, 0))
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setMargin(3)
        self.gridLayout.setSpacing(3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.stopButton = QtGui.QPushButton(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopButton.sizePolicy().hasHeightForWidth())
        self.stopButton.setSizePolicy(sizePolicy)
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.gridLayout.addWidget(self.stopButton, 1, 1, 1, 1)
        self.singleShotButton = QtGui.QPushButton(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.singleShotButton.sizePolicy().hasHeightForWidth())
        self.singleShotButton.setSizePolicy(sizePolicy)
        self.singleShotButton.setObjectName(_fromUtf8("singleShotButton"))
        self.gridLayout.addWidget(self.singleShotButton, 3, 0, 1, 2)
        self.startButton = QtGui.QPushButton(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)
        self.startButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.gridLayout.addWidget(self.startButton, 1, 0, 1, 1)
        self.controlsWidget.setWidget(self.dockWidgetContents)
        mainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.controlsWidget)
        self.voltagesWidget = QtGui.QDockWidget(mainWindow)
        self.voltagesWidget.setMaximumSize(QtCore.QSize(200, 400))
        self.voltagesWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.voltagesWidget.setObjectName(_fromUtf8("voltagesWidget"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.dockWidgetContents_3)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.SampleStartVoltageUnits = QtGui.QComboBox(self.groupBox)
        self.SampleStartVoltageUnits.setObjectName(_fromUtf8("SampleStartVoltageUnits"))
        self.SampleStartVoltageUnits.addItem(_fromUtf8(""))
        self.SampleStartVoltageUnits.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.SampleStartVoltageUnits, 0, 2, 1, 1)
        self.SampleStartVoltage = QtGui.QDoubleSpinBox(self.groupBox)
        self.SampleStartVoltage.setObjectName(_fromUtf8("SampleStartVoltage"))
        self.gridLayout_4.addWidget(self.SampleStartVoltage, 0, 1, 1, 1)
        self.SampleStepVoltage = QtGui.QDoubleSpinBox(self.groupBox)
        self.SampleStepVoltage.setObjectName(_fromUtf8("SampleStepVoltage"))
        self.gridLayout_4.addWidget(self.SampleStepVoltage, 2, 1, 1, 1)
        self.SampleStepVoltageUnits = QtGui.QComboBox(self.groupBox)
        self.SampleStepVoltageUnits.setObjectName(_fromUtf8("SampleStepVoltageUnits"))
        self.SampleStepVoltageUnits.addItem(_fromUtf8(""))
        self.SampleStepVoltageUnits.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.SampleStepVoltageUnits, 2, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 2, 0, 1, 1)
        self.SampleStopVoltageUnits = QtGui.QComboBox(self.groupBox)
        self.SampleStopVoltageUnits.setObjectName(_fromUtf8("SampleStopVoltageUnits"))
        self.SampleStopVoltageUnits.addItem(_fromUtf8(""))
        self.SampleStopVoltageUnits.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.SampleStopVoltageUnits, 1, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 1, 0, 1, 1)
        self.SampleStopVoltage = QtGui.QDoubleSpinBox(self.groupBox)
        self.SampleStopVoltage.setObjectName(_fromUtf8("SampleStopVoltage"))
        self.gridLayout_4.addWidget(self.SampleStopVoltage, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.dockWidgetContents_3)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.GateStopVoltageUnits = QtGui.QComboBox(self.groupBox_2)
        self.GateStopVoltageUnits.setObjectName(_fromUtf8("GateStopVoltageUnits"))
        self.GateStopVoltageUnits.addItem(_fromUtf8(""))
        self.GateStopVoltageUnits.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.GateStopVoltageUnits, 2, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 1)
        self.GateStepVoltageUnits = QtGui.QComboBox(self.groupBox_2)
        self.GateStepVoltageUnits.setObjectName(_fromUtf8("GateStepVoltageUnits"))
        self.GateStepVoltageUnits.addItem(_fromUtf8(""))
        self.GateStepVoltageUnits.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.GateStepVoltageUnits, 3, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 3, 0, 1, 1)
        self.GateStepVoltage = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.GateStepVoltage.setObjectName(_fromUtf8("GateStepVoltage"))
        self.gridLayout_3.addWidget(self.GateStepVoltage, 3, 1, 1, 1)
        self.GateStopVoltage = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.GateStopVoltage.setObjectName(_fromUtf8("GateStopVoltage"))
        self.gridLayout_3.addWidget(self.GateStopVoltage, 2, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.GateStartVoltage = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.GateStartVoltage.setObjectName(_fromUtf8("GateStartVoltage"))
        self.gridLayout_3.addWidget(self.GateStartVoltage, 1, 1, 1, 1)
        self.GateStartVoltageUnits = QtGui.QComboBox(self.groupBox_2)
        self.GateStartVoltageUnits.setObjectName(_fromUtf8("GateStartVoltageUnits"))
        self.GateStartVoltageUnits.addItem(_fromUtf8(""))
        self.GateStartVoltageUnits.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.GateStartVoltageUnits, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.dockWidgetContents_3)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_5.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_5.addWidget(self.label_10, 2, 0, 1, 1)
        self.GateVoltage = QtGui.QLineEdit(self.groupBox_3)
        self.GateVoltage.setEnabled(False)
        self.GateVoltage.setObjectName(_fromUtf8("GateVoltage"))
        self.gridLayout_5.addWidget(self.GateVoltage, 2, 1, 1, 1)
        self.SampleCurrent = QtGui.QLineEdit(self.groupBox_3)
        self.SampleCurrent.setEnabled(False)
        self.SampleCurrent.setObjectName(_fromUtf8("SampleCurrent"))
        self.gridLayout_5.addWidget(self.SampleCurrent, 1, 1, 1, 1)
        self.SampleVoltage = QtGui.QLineEdit(self.groupBox_3)
        self.SampleVoltage.setEnabled(False)
        self.SampleVoltage.setObjectName(_fromUtf8("SampleVoltage"))
        self.gridLayout_5.addWidget(self.SampleVoltage, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_5.addWidget(self.label_9, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.voltagesWidget.setWidget(self.dockWidgetContents_3)
        mainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.voltagesWidget)
        self.actionWorkingFolder = QtGui.QAction(mainWindow)
        self.actionWorkingFolder.setObjectName(_fromUtf8("actionWorkingFolder"))
        self.actionExit = QtGui.QAction(mainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionRestoreWindows = QtGui.QAction(mainWindow)
        self.actionRestoreWindows.setObjectName(_fromUtf8("actionRestoreWindows"))
        self.actionAbout = QtGui.QAction(mainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionFrequencySettings = QtGui.QAction(mainWindow)
        self.actionFrequencySettings.setObjectName(_fromUtf8("actionFrequencySettings"))
        self.actionAllSettings = QtGui.QAction(mainWindow)
        self.actionAllSettings.setObjectName(_fromUtf8("actionAllSettings"))
        self.actionFrequency_range = QtGui.QAction(mainWindow)
        self.actionFrequency_range.setObjectName(_fromUtf8("actionFrequency_range"))
        self.actionVoltage_range = QtGui.QAction(mainWindow)
        self.actionVoltage_range.setObjectName(_fromUtf8("actionVoltage_range"))
        self.actionAll = QtGui.QAction(mainWindow)
        self.actionAll.setObjectName(_fromUtf8("actionAll"))
        self.actionSaveAll = QtGui.QAction(mainWindow)
        self.actionSaveAll.setObjectName(_fromUtf8("actionSaveAll"))
        self.actionFrequencies = QtGui.QAction(mainWindow)
        self.actionFrequencies.setObjectName(_fromUtf8("actionFrequencies"))
        self.actionVoltages = QtGui.QAction(mainWindow)
        self.actionVoltages.setObjectName(_fromUtf8("actionVoltages"))
        self.actionSaveAll_2 = QtGui.QAction(mainWindow)
        self.actionSaveAll_2.setObjectName(_fromUtf8("actionSaveAll_2"))
        self.actionFrequencies_2 = QtGui.QAction(mainWindow)
        self.actionFrequencies_2.setObjectName(_fromUtf8("actionFrequencies_2"))
        self.actionVoltages_2 = QtGui.QAction(mainWindow)
        self.actionVoltages_2.setObjectName(_fromUtf8("actionVoltages_2"))
        self.actionLoadAll = QtGui.QAction(mainWindow)
        self.actionLoadAll.setObjectName(_fromUtf8("actionLoadAll"))
        self.actionChannelSettings = QtGui.QAction(mainWindow)
        self.actionChannelSettings.setObjectName(_fromUtf8("actionChannelSettings"))
        self.actionOutputSettings = QtGui.QAction(mainWindow)
        self.actionOutputSettings.setObjectName(_fromUtf8("actionOutputSettings"))
        self.actionAcquisitionSettings = QtGui.QAction(mainWindow)
        self.actionAcquisitionSettings.setObjectName(_fromUtf8("actionAcquisitionSettings"))
        self.menuFile.addAction(self.actionWorkingFolder)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuWindow.addAction(self.actionRestoreWindows)
        self.menuHelp.addAction(self.actionAbout)
        self.menuSave_2.addAction(self.actionFrequencies)
        self.menuSave_2.addAction(self.actionVoltages)
        self.menuSave_2.addAction(self.actionSaveAll_2)
        self.menuLoad_2.addAction(self.actionFrequencies_2)
        self.menuLoad_2.addAction(self.actionVoltages_2)
        self.menuLoad_2.addAction(self.actionLoadAll)
        self.menuSettings.addAction(self.actionChannelSettings)
        self.menuSettings.addAction(self.actionOutputSettings)
        self.menuSettings.addAction(self.actionAcquisitionSettings)
        self.menuSettings.addAction(self.menuSave_2.menuAction())
        self.menuSettings.addAction(self.menuLoad_2.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(_translate("mainWindow", "PyFANS", None))
        self.menuFile.setTitle(_translate("mainWindow", "File", None))
        self.menuWindow.setTitle(_translate("mainWindow", "Window", None))
        self.menuHelp.setTitle(_translate("mainWindow", "Help", None))
        self.menuSettings.setTitle(_translate("mainWindow", "Settings", None))
        self.menuSave_2.setTitle(_translate("mainWindow", "Save", None))
        self.menuLoad_2.setTitle(_translate("mainWindow", "Load", None))
        self.controlsWidget.setWindowTitle(_translate("mainWindow", "Controls", None))
        self.stopButton.setText(_translate("mainWindow", "Stop", None))
        self.singleShotButton.setText(_translate("mainWindow", "Single shot", None))
        self.startButton.setText(_translate("mainWindow", "Start", None))
        self.voltagesWidget.setWindowTitle(_translate("mainWindow", "Voltages", None))
        self.groupBox.setTitle(_translate("mainWindow", "Drain-Source Voltage", None))
        self.label_3.setText(_translate("mainWindow", "Start", None))
        self.SampleStartVoltageUnits.setItemText(0, _translate("mainWindow", "V", None))
        self.SampleStartVoltageUnits.setItemText(1, _translate("mainWindow", "mV", None))
        self.SampleStepVoltageUnits.setItemText(0, _translate("mainWindow", "V", None))
        self.SampleStepVoltageUnits.setItemText(1, _translate("mainWindow", "mV", None))
        self.label_5.setText(_translate("mainWindow", "Step", None))
        self.SampleStopVoltageUnits.setItemText(0, _translate("mainWindow", "V", None))
        self.SampleStopVoltageUnits.setItemText(1, _translate("mainWindow", "mV", None))
        self.label_4.setText(_translate("mainWindow", "Stop", None))
        self.groupBox_2.setTitle(_translate("mainWindow", "Gate Voltage", None))
        self.GateStopVoltageUnits.setItemText(0, _translate("mainWindow", "V", None))
        self.GateStopVoltageUnits.setItemText(1, _translate("mainWindow", "mV", None))
        self.label_8.setText(_translate("mainWindow", "Stop", None))
        self.GateStepVoltageUnits.setItemText(0, _translate("mainWindow", "V", None))
        self.GateStepVoltageUnits.setItemText(1, _translate("mainWindow", "mV", None))
        self.label_7.setText(_translate("mainWindow", "Step", None))
        self.label_6.setText(_translate("mainWindow", "Start", None))
        self.GateStartVoltageUnits.setItemText(0, _translate("mainWindow", "V", None))
        self.GateStartVoltageUnits.setItemText(1, _translate("mainWindow", "mV", None))
        self.groupBox_3.setTitle(_translate("mainWindow", "Current Values", None))
        self.label_11.setText(_translate("mainWindow", "Sample Current", None))
        self.label_10.setText(_translate("mainWindow", "Gate Voltage", None))
        self.label_9.setText(_translate("mainWindow", "Sample Voltage", None))
        self.actionWorkingFolder.setText(_translate("mainWindow", "WorkingFolder", None))
        self.actionExit.setText(_translate("mainWindow", "Exit", None))
        self.actionRestoreWindows.setText(_translate("mainWindow", "Restore", None))
        self.actionAbout.setText(_translate("mainWindow", "About", None))
        self.actionFrequencySettings.setText(_translate("mainWindow", "FrequencySettings", None))
        self.actionAllSettings.setText(_translate("mainWindow", "AllSettings", None))
        self.actionFrequency_range.setText(_translate("mainWindow", "Frequency range", None))
        self.actionVoltage_range.setText(_translate("mainWindow", "Voltage range", None))
        self.actionAll.setText(_translate("mainWindow", "All", None))
        self.actionSaveAll.setText(_translate("mainWindow", "SaveAll", None))
        self.actionFrequencies.setText(_translate("mainWindow", "Frequencies", None))
        self.actionVoltages.setText(_translate("mainWindow", "Voltages", None))
        self.actionSaveAll_2.setText(_translate("mainWindow", "All", None))
        self.actionFrequencies_2.setText(_translate("mainWindow", "Frequencies", None))
        self.actionVoltages_2.setText(_translate("mainWindow", "Voltages", None))
        self.actionLoadAll.setText(_translate("mainWindow", "All", None))
        self.actionChannelSettings.setText(_translate("mainWindow", "Channel settings", None))
        self.actionOutputSettings.setText(_translate("mainWindow", "Output settings", None))
        self.actionAcquisitionSettings.setText(_translate("mainWindow", "Acquisition settings", None))

from pyqtgraph import GraphicsLayoutWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    mainWindow = QtGui.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())

