# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Programming\Repositories\PyFANS\PyFANS\UI\UI_NoiseMeasurement_v5_3.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_NoiseMeasurement(object):
    def setupUi(self, NoiseMeasurement):
        NoiseMeasurement.setObjectName(_fromUtf8("NoiseMeasurement"))
        NoiseMeasurement.resize(1030, 976)
        self.centralwidget = QtGui.QWidget(NoiseMeasurement)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.ui_plot = GraphicsLayoutWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_plot.sizePolicy().hasHeightForWidth())
        self.ui_plot.setSizePolicy(sizePolicy)
        self.ui_plot.setObjectName(_fromUtf8("ui_plot"))
        self.horizontalLayout.addWidget(self.ui_plot)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.ui_settings_frame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_settings_frame.sizePolicy().hasHeightForWidth())
        self.ui_settings_frame.setSizePolicy(sizePolicy)
        self.ui_settings_frame.setMaximumSize(QtCore.QSize(350, 16777215))
        self.ui_settings_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.ui_settings_frame.setFrameShadow(QtGui.QFrame.Plain)
        self.ui_settings_frame.setObjectName(_fromUtf8("ui_settings_frame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.ui_settings_frame)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 7, 0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.ui_calibrate = QtGui.QCheckBox(self.ui_settings_frame)
        self.ui_calibrate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_calibrate.sizePolicy().hasHeightForWidth())
        self.ui_calibrate.setSizePolicy(sizePolicy)
        self.ui_calibrate.setObjectName(_fromUtf8("ui_calibrate"))
        self.gridLayout_2.addWidget(self.ui_calibrate, 0, 0, 1, 1)
        self.ui_open_hardware_settings = QtGui.QPushButton(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_open_hardware_settings.sizePolicy().hasHeightForWidth())
        self.ui_open_hardware_settings.setSizePolicy(sizePolicy)
        self.ui_open_hardware_settings.setObjectName(_fromUtf8("ui_open_hardware_settings"))
        self.gridLayout_2.addWidget(self.ui_open_hardware_settings, 0, 1, 1, 1)
        self.ui_overload_reject = QtGui.QCheckBox(self.ui_settings_frame)
        self.ui_overload_reject.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_overload_reject.sizePolicy().hasHeightForWidth())
        self.ui_overload_reject.setSizePolicy(sizePolicy)
        self.ui_overload_reject.setObjectName(_fromUtf8("ui_overload_reject"))
        self.gridLayout_2.addWidget(self.ui_overload_reject, 1, 0, 1, 1)
        self.ui_simulate = QtGui.QCheckBox(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_simulate.sizePolicy().hasHeightForWidth())
        self.ui_simulate.setSizePolicy(sizePolicy)
        self.ui_simulate.setObjectName(_fromUtf8("ui_simulate"))
        self.gridLayout_2.addWidget(self.ui_simulate, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.line = QtGui.QFrame(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setSpacing(4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.ui_averages = QtGui.QSpinBox(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_averages.sizePolicy().hasHeightForWidth())
        self.ui_averages.setSizePolicy(sizePolicy)
        self.ui_averages.setMinimum(1)
        self.ui_averages.setMaximum(500000)
        self.ui_averages.setProperty("value", 100)
        self.ui_averages.setObjectName(_fromUtf8("ui_averages"))
        self.gridLayout_5.addWidget(self.ui_averages, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_5.addWidget(self.label_2, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.line_2 = QtGui.QFrame(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setSpacing(4)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.ui_second_amp_coeff = QtGui.QComboBox(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_second_amp_coeff.sizePolicy().hasHeightForWidth())
        self.ui_second_amp_coeff.setSizePolicy(sizePolicy)
        self.ui_second_amp_coeff.setFrame(True)
        self.ui_second_amp_coeff.setObjectName(_fromUtf8("ui_second_amp_coeff"))
        self.ui_second_amp_coeff.addItem(_fromUtf8(""))
        self.ui_second_amp_coeff.addItem(_fromUtf8(""))
        self.ui_second_amp_coeff.addItem(_fromUtf8(""))
        self.ui_second_amp_coeff.addItem(_fromUtf8(""))
        self.ui_second_amp_coeff.addItem(_fromUtf8(""))
        self.ui_second_amp_coeff.addItem(_fromUtf8(""))
        self.ui_second_amp_coeff.addItem(_fromUtf8(""))
        self.ui_second_amp_coeff.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.ui_second_amp_coeff, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_6.addWidget(self.label_3, 1, 1, 1, 1)
        self.ui_use_homemade_amplifier = QtGui.QCheckBox(self.ui_settings_frame)
        self.ui_use_homemade_amplifier.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_use_homemade_amplifier.sizePolicy().hasHeightForWidth())
        self.ui_use_homemade_amplifier.setSizePolicy(sizePolicy)
        self.ui_use_homemade_amplifier.setChecked(True)
        self.ui_use_homemade_amplifier.setObjectName(_fromUtf8("ui_use_homemade_amplifier"))
        self.gridLayout_6.addWidget(self.ui_use_homemade_amplifier, 0, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout_6)
        self.line_3 = QtGui.QFrame(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout.addWidget(self.line_3)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setSpacing(4)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.ui_temp_range_button = QtGui.QPushButton(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_temp_range_button.sizePolicy().hasHeightForWidth())
        self.ui_temp_range_button.setSizePolicy(sizePolicy)
        self.ui_temp_range_button.setObjectName(_fromUtf8("ui_temp_range_button"))
        self.gridLayout_7.addWidget(self.ui_temp_range_button, 3, 3, 1, 1)
        self.ui_temperature = QtGui.QLineEdit(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_temperature.sizePolicy().hasHeightForWidth())
        self.ui_temperature.setSizePolicy(sizePolicy)
        self.ui_temperature.setMaximumSize(QtCore.QSize(110, 16777215))
        self.ui_temperature.setObjectName(_fromUtf8("ui_temperature"))
        self.gridLayout_7.addWidget(self.ui_temperature, 3, 1, 1, 1)
        self.ui_use_set_temperature_range = QtGui.QCheckBox(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_use_set_temperature_range.sizePolicy().hasHeightForWidth())
        self.ui_use_set_temperature_range.setSizePolicy(sizePolicy)
        self.ui_use_set_temperature_range.setAutoExclusive(True)
        self.ui_use_set_temperature_range.setObjectName(_fromUtf8("ui_use_set_temperature_range"))
        self.gridLayout_7.addWidget(self.ui_use_set_temperature_range, 3, 2, 1, 1)
        self.ui_set_temperature_single = QtGui.QCheckBox(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_set_temperature_single.sizePolicy().hasHeightForWidth())
        self.ui_set_temperature_single.setSizePolicy(sizePolicy)
        self.ui_set_temperature_single.setAutoExclusive(True)
        self.ui_set_temperature_single.setObjectName(_fromUtf8("ui_set_temperature_single"))
        self.gridLayout_7.addWidget(self.ui_set_temperature_single, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.ui_use_smart_spectrum = QtGui.QCheckBox(self.ui_settings_frame)
        self.ui_use_smart_spectrum.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_use_smart_spectrum.sizePolicy().hasHeightForWidth())
        self.ui_use_smart_spectrum.setSizePolicy(sizePolicy)
        self.ui_use_smart_spectrum.setObjectName(_fromUtf8("ui_use_smart_spectrum"))
        self.horizontalLayout_5.addWidget(self.ui_use_smart_spectrum)
        self.ui_need_meas_temp = QtGui.QCheckBox(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_need_meas_temp.sizePolicy().hasHeightForWidth())
        self.ui_need_meas_temp.setSizePolicy(sizePolicy)
        self.ui_need_meas_temp.setObjectName(_fromUtf8("ui_need_meas_temp"))
        self.horizontalLayout_5.addWidget(self.ui_need_meas_temp)
        self.ui_automated_temperature = QtGui.QCheckBox(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_automated_temperature.sizePolicy().hasHeightForWidth())
        self.ui_automated_temperature.setSizePolicy(sizePolicy)
        self.ui_automated_temperature.setObjectName(_fromUtf8("ui_automated_temperature"))
        self.horizontalLayout_5.addWidget(self.ui_automated_temperature)
        self.gridLayout_7.addLayout(self.horizontalLayout_5, 2, 0, 1, 4)
        self.verticalLayout.addLayout(self.gridLayout_7)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.ui_load_resistance = QtGui.QLineEdit(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_load_resistance.sizePolicy().hasHeightForWidth())
        self.ui_load_resistance.setSizePolicy(sizePolicy)
        self.ui_load_resistance.setObjectName(_fromUtf8("ui_load_resistance"))
        self.horizontalLayout_3.addWidget(self.ui_load_resistance)
        self.label_4 = QtGui.QLabel(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line_4 = QtGui.QFrame(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_4.sizePolicy().hasHeightForWidth())
        self.line_4.setSizePolicy(sizePolicy)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout.addWidget(self.line_4)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setSpacing(4)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.ui_use_dut_selector = QtGui.QCheckBox(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_use_dut_selector.sizePolicy().hasHeightForWidth())
        self.ui_use_dut_selector.setSizePolicy(sizePolicy)
        self.ui_use_dut_selector.setObjectName(_fromUtf8("ui_use_dut_selector"))
        self.gridLayout_9.addWidget(self.ui_use_dut_selector, 1, 0, 1, 1)
        self.ui_transistorSelector = QtGui.QPushButton(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_transistorSelector.sizePolicy().hasHeightForWidth())
        self.ui_transistorSelector.setSizePolicy(sizePolicy)
        self.ui_transistorSelector.setObjectName(_fromUtf8("ui_transistorSelector"))
        self.gridLayout_9.addWidget(self.ui_transistorSelector, 1, 1, 1, 1)
        self.ui_meas_gated_structure = QtGui.QCheckBox(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_meas_gated_structure.sizePolicy().hasHeightForWidth())
        self.ui_meas_gated_structure.setSizePolicy(sizePolicy)
        self.ui_meas_gated_structure.setChecked(True)
        self.ui_meas_gated_structure.setObjectName(_fromUtf8("ui_meas_gated_structure"))
        self.gridLayout_9.addWidget(self.ui_meas_gated_structure, 0, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout_9)
        self.line_5 = QtGui.QFrame(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_5.sizePolicy().hasHeightForWidth())
        self.line_5.setSizePolicy(sizePolicy)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout.addWidget(self.line_5)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.ui_use_automated_voltage_control = QtGui.QCheckBox(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_use_automated_voltage_control.sizePolicy().hasHeightForWidth())
        self.ui_use_automated_voltage_control.setSizePolicy(sizePolicy)
        self.ui_use_automated_voltage_control.setObjectName(_fromUtf8("ui_use_automated_voltage_control"))
        self.horizontalLayout_2.addWidget(self.ui_use_automated_voltage_control)
        self.ui_voltage_control = QtGui.QPushButton(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_voltage_control.sizePolicy().hasHeightForWidth())
        self.ui_voltage_control.setSizePolicy(sizePolicy)
        self.ui_voltage_control.setObjectName(_fromUtf8("ui_voltage_control"))
        self.horizontalLayout_2.addWidget(self.ui_voltage_control)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_18 = QtGui.QLabel(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_4.addWidget(self.label_18)
        self.ui_meas_characteristic_type = QtGui.QComboBox(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_meas_characteristic_type.sizePolicy().hasHeightForWidth())
        self.ui_meas_characteristic_type.setSizePolicy(sizePolicy)
        self.ui_meas_characteristic_type.setObjectName(_fromUtf8("ui_meas_characteristic_type"))
        self.ui_meas_characteristic_type.addItem(_fromUtf8(""))
        self.ui_meas_characteristic_type.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.ui_meas_characteristic_type)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.line_7 = QtGui.QFrame(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_7.sizePolicy().hasHeightForWidth())
        self.line_7.setSizePolicy(sizePolicy)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.verticalLayout.addWidget(self.line_7)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_8.setSpacing(4)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.VfgRange = QtGui.QPushButton(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VfgRange.sizePolicy().hasHeightForWidth())
        self.VfgRange.setSizePolicy(sizePolicy)
        self.VfgRange.setObjectName(_fromUtf8("VfgRange"))
        self.gridLayout_8.addWidget(self.VfgRange, 1, 3, 1, 1)
        self.ui_use_set_vds_range = QtGui.QCheckBox(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_use_set_vds_range.sizePolicy().hasHeightForWidth())
        self.ui_use_set_vds_range.setSizePolicy(sizePolicy)
        self.ui_use_set_vds_range.setAutoExclusive(True)
        self.ui_use_set_vds_range.setObjectName(_fromUtf8("ui_use_set_vds_range"))
        self.gridLayout_8.addWidget(self.ui_use_set_vds_range, 0, 2, 1, 1)
        self.ui_drain_source_voltage = QtGui.QLineEdit(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_drain_source_voltage.sizePolicy().hasHeightForWidth())
        self.ui_drain_source_voltage.setSizePolicy(sizePolicy)
        self.ui_drain_source_voltage.setMaximumSize(QtCore.QSize(110, 16777215))
        self.ui_drain_source_voltage.setObjectName(_fromUtf8("ui_drain_source_voltage"))
        self.gridLayout_8.addWidget(self.ui_drain_source_voltage, 0, 1, 1, 1)
        self.VdsRange = QtGui.QPushButton(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VdsRange.sizePolicy().hasHeightForWidth())
        self.VdsRange.setSizePolicy(sizePolicy)
        self.VdsRange.setObjectName(_fromUtf8("VdsRange"))
        self.gridLayout_8.addWidget(self.VdsRange, 0, 3, 1, 1)
        self.ui_use_set_vfg_range = QtGui.QCheckBox(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_use_set_vfg_range.sizePolicy().hasHeightForWidth())
        self.ui_use_set_vfg_range.setSizePolicy(sizePolicy)
        self.ui_use_set_vfg_range.setAutoExclusive(True)
        self.ui_use_set_vfg_range.setObjectName(_fromUtf8("ui_use_set_vfg_range"))
        self.gridLayout_8.addWidget(self.ui_use_set_vfg_range, 1, 2, 1, 1)
        self.ui_front_gate_voltage = QtGui.QLineEdit(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_front_gate_voltage.sizePolicy().hasHeightForWidth())
        self.ui_front_gate_voltage.setSizePolicy(sizePolicy)
        self.ui_front_gate_voltage.setMaximumSize(QtCore.QSize(110, 16777215))
        self.ui_front_gate_voltage.setObjectName(_fromUtf8("ui_front_gate_voltage"))
        self.gridLayout_8.addWidget(self.ui_front_gate_voltage, 1, 1, 1, 1)
        self.ui_set_gate_source_voltage = QtGui.QCheckBox(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_set_gate_source_voltage.sizePolicy().hasHeightForWidth())
        self.ui_set_gate_source_voltage.setSizePolicy(sizePolicy)
        self.ui_set_gate_source_voltage.setAutoExclusive(True)
        self.ui_set_gate_source_voltage.setObjectName(_fromUtf8("ui_set_gate_source_voltage"))
        self.gridLayout_8.addWidget(self.ui_set_gate_source_voltage, 1, 0, 1, 1)
        self.ui_set_drain_source_voltage = QtGui.QCheckBox(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_set_drain_source_voltage.sizePolicy().hasHeightForWidth())
        self.ui_set_drain_source_voltage.setSizePolicy(sizePolicy)
        self.ui_set_drain_source_voltage.setAutoExclusive(True)
        self.ui_set_drain_source_voltage.setObjectName(_fromUtf8("ui_set_drain_source_voltage"))
        self.gridLayout_8.addWidget(self.ui_set_drain_source_voltage, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_8)
        self.line_6 = QtGui.QFrame(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_6.sizePolicy().hasHeightForWidth())
        self.line_6.setSizePolicy(sizePolicy)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.verticalLayout.addWidget(self.line_6)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setSpacing(4)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label = QtGui.QLabel(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_11.addWidget(self.label, 0, 0, 1, 1)
        self.ui_timetrace_mode = QtGui.QComboBox(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_timetrace_mode.sizePolicy().hasHeightForWidth())
        self.ui_timetrace_mode.setSizePolicy(sizePolicy)
        self.ui_timetrace_mode.setObjectName(_fromUtf8("ui_timetrace_mode"))
        self.ui_timetrace_mode.addItem(_fromUtf8(""))
        self.ui_timetrace_mode.addItem(_fromUtf8(""))
        self.ui_timetrace_mode.addItem(_fromUtf8(""))
        self.gridLayout_11.addWidget(self.ui_timetrace_mode, 0, 1, 1, 1)
        self.ui_timetrace_length = QtGui.QSpinBox(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_timetrace_length.sizePolicy().hasHeightForWidth())
        self.ui_timetrace_length.setSizePolicy(sizePolicy)
        self.ui_timetrace_length.setMinimum(1)
        self.ui_timetrace_length.setMaximum(999999999)
        self.ui_timetrace_length.setObjectName(_fromUtf8("ui_timetrace_length"))
        self.gridLayout_11.addWidget(self.ui_timetrace_length, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.ui_set_zero_after_measurement = QtGui.QCheckBox(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_set_zero_after_measurement.sizePolicy().hasHeightForWidth())
        self.ui_set_zero_after_measurement.setSizePolicy(sizePolicy)
        self.ui_set_zero_after_measurement.setObjectName(_fromUtf8("ui_set_zero_after_measurement"))
        self.gridLayout_3.addWidget(self.ui_set_zero_after_measurement, 0, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.line_8 = QtGui.QFrame(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_8.sizePolicy().hasHeightForWidth())
        self.line_8.setSizePolicy(sizePolicy)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.verticalLayout.addWidget(self.line_8)
        self.groupBox = QtGui.QGroupBox(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setMargin(4)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.line_10 = QtGui.QFrame(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_10.sizePolicy().hasHeightForWidth())
        self.line_10.setSizePolicy(sizePolicy)
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.gridLayout.addWidget(self.line_10, 1, 2, 1, 3)
        self.ui_sample_current_end = QtGui.QLineEdit(self.groupBox)
        self.ui_sample_current_end.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_sample_current_end.sizePolicy().hasHeightForWidth())
        self.ui_sample_current_end.setSizePolicy(sizePolicy)
        self.ui_sample_current_end.setText(_fromUtf8(""))
        self.ui_sample_current_end.setReadOnly(True)
        self.ui_sample_current_end.setObjectName(_fromUtf8("ui_sample_current_end"))
        self.gridLayout.addWidget(self.ui_sample_current_end, 5, 4, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 6, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 4, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.ui_sample_current_start = QtGui.QLineEdit(self.groupBox)
        self.ui_sample_current_start.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_sample_current_start.sizePolicy().hasHeightForWidth())
        self.ui_sample_current_start.setSizePolicy(sizePolicy)
        self.ui_sample_current_start.setText(_fromUtf8(""))
        self.ui_sample_current_start.setReadOnly(True)
        self.ui_sample_current_start.setObjectName(_fromUtf8("ui_sample_current_start"))
        self.gridLayout.addWidget(self.ui_sample_current_start, 5, 2, 1, 1)
        self.ui_main_voltage_end = QtGui.QLineEdit(self.groupBox)
        self.ui_main_voltage_end.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_main_voltage_end.sizePolicy().hasHeightForWidth())
        self.ui_main_voltage_end.setSizePolicy(sizePolicy)
        self.ui_main_voltage_end.setReadOnly(True)
        self.ui_main_voltage_end.setObjectName(_fromUtf8("ui_main_voltage_end"))
        self.gridLayout.addWidget(self.ui_main_voltage_end, 3, 4, 1, 1)
        self.ui_sample_voltage_end = QtGui.QLineEdit(self.groupBox)
        self.ui_sample_voltage_end.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_sample_voltage_end.sizePolicy().hasHeightForWidth())
        self.ui_sample_voltage_end.setSizePolicy(sizePolicy)
        self.ui_sample_voltage_end.setReadOnly(True)
        self.ui_sample_voltage_end.setObjectName(_fromUtf8("ui_sample_voltage_end"))
        self.gridLayout.addWidget(self.ui_sample_voltage_end, 2, 4, 1, 1)
        self.ui_main_voltage_start = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_main_voltage_start.sizePolicy().hasHeightForWidth())
        self.ui_main_voltage_start.setSizePolicy(sizePolicy)
        self.ui_main_voltage_start.setText(_fromUtf8(""))
        self.ui_main_voltage_start.setReadOnly(True)
        self.ui_main_voltage_start.setObjectName(_fromUtf8("ui_main_voltage_start"))
        self.gridLayout.addWidget(self.ui_main_voltage_start, 3, 2, 1, 1)
        self.ui_sample_resistance_start = QtGui.QLineEdit(self.groupBox)
        self.ui_sample_resistance_start.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_sample_resistance_start.sizePolicy().hasHeightForWidth())
        self.ui_sample_resistance_start.setSizePolicy(sizePolicy)
        self.ui_sample_resistance_start.setText(_fromUtf8(""))
        self.ui_sample_resistance_start.setReadOnly(True)
        self.ui_sample_resistance_start.setObjectName(_fromUtf8("ui_sample_resistance_start"))
        self.gridLayout.addWidget(self.ui_sample_resistance_start, 6, 2, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout.addWidget(self.label_19, 3, 0, 1, 1)
        self.ui_front_gate_voltage_start = QtGui.QLineEdit(self.groupBox)
        self.ui_front_gate_voltage_start.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_front_gate_voltage_start.sizePolicy().hasHeightForWidth())
        self.ui_front_gate_voltage_start.setSizePolicy(sizePolicy)
        self.ui_front_gate_voltage_start.setText(_fromUtf8(""))
        self.ui_front_gate_voltage_start.setReadOnly(True)
        self.ui_front_gate_voltage_start.setObjectName(_fromUtf8("ui_front_gate_voltage_start"))
        self.gridLayout.addWidget(self.ui_front_gate_voltage_start, 4, 2, 1, 1)
        self.ui_front_gate_voltage_end = QtGui.QLineEdit(self.groupBox)
        self.ui_front_gate_voltage_end.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_front_gate_voltage_end.sizePolicy().hasHeightForWidth())
        self.ui_front_gate_voltage_end.setSizePolicy(sizePolicy)
        self.ui_front_gate_voltage_end.setText(_fromUtf8(""))
        self.ui_front_gate_voltage_end.setReadOnly(True)
        self.ui_front_gate_voltage_end.setObjectName(_fromUtf8("ui_front_gate_voltage_end"))
        self.gridLayout.addWidget(self.ui_front_gate_voltage_end, 4, 4, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 5, 0, 1, 1)
        self.ui_sample_voltage_start = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_sample_voltage_start.sizePolicy().hasHeightForWidth())
        self.ui_sample_voltage_start.setSizePolicy(sizePolicy)
        self.ui_sample_voltage_start.setText(_fromUtf8(""))
        self.ui_sample_voltage_start.setReadOnly(True)
        self.ui_sample_voltage_start.setObjectName(_fromUtf8("ui_sample_voltage_start"))
        self.gridLayout.addWidget(self.ui_sample_voltage_start, 2, 2, 1, 1)
        self.ui_sample_resistance_end = QtGui.QLineEdit(self.groupBox)
        self.ui_sample_resistance_end.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_sample_resistance_end.sizePolicy().hasHeightForWidth())
        self.ui_sample_resistance_end.setSizePolicy(sizePolicy)
        self.ui_sample_resistance_end.setText(_fromUtf8(""))
        self.ui_sample_resistance_end.setReadOnly(True)
        self.ui_sample_resistance_end.setObjectName(_fromUtf8("ui_sample_resistance_end"))
        self.gridLayout.addWidget(self.ui_sample_resistance_end, 6, 4, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        self.ui_temperature_start = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_temperature_start.sizePolicy().hasHeightForWidth())
        self.ui_temperature_start.setSizePolicy(sizePolicy)
        self.ui_temperature_start.setReadOnly(True)
        self.ui_temperature_start.setObjectName(_fromUtf8("ui_temperature_start"))
        self.gridLayout.addWidget(self.ui_temperature_start, 7, 2, 1, 1)
        self.ui_temperature_end = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_temperature_end.sizePolicy().hasHeightForWidth())
        self.ui_temperature_end.setSizePolicy(sizePolicy)
        self.ui_temperature_end.setReadOnly(True)
        self.ui_temperature_end.setObjectName(_fromUtf8("ui_temperature_end"))
        self.gridLayout.addWidget(self.ui_temperature_end, 7, 4, 1, 1)
        self.line_12 = QtGui.QFrame(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_12.sizePolicy().hasHeightForWidth())
        self.line_12.setSizePolicy(sizePolicy)
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.gridLayout.addWidget(self.line_12, 1, 0, 1, 1)
        self.line_11 = QtGui.QFrame(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_11.sizePolicy().hasHeightForWidth())
        self.line_11.setSizePolicy(sizePolicy)
        self.line_11.setFrameShape(QtGui.QFrame.VLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.gridLayout.addWidget(self.line_11, 0, 1, 1, 1)
        self.line_13 = QtGui.QFrame(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_13.sizePolicy().hasHeightForWidth())
        self.line_13.setSizePolicy(sizePolicy)
        self.line_13.setFrameShape(QtGui.QFrame.VLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.gridLayout.addWidget(self.line_13, 0, 3, 1, 1)
        self.line_9 = QtGui.QFrame(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_9.sizePolicy().hasHeightForWidth())
        self.line_9.setSizePolicy(sizePolicy)
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.gridLayout.addWidget(self.line_9, 2, 1, 6, 1)
        self.line_14 = QtGui.QFrame(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_14.sizePolicy().hasHeightForWidth())
        self.line_14.setSizePolicy(sizePolicy)
        self.line_14.setFrameShape(QtGui.QFrame.VLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName(_fromUtf8("line_14"))
        self.gridLayout.addWidget(self.line_14, 2, 3, 6, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.ui_settings_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setMargin(4)
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_4.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_4.addWidget(self.label_13, 1, 0, 1, 1)
        self.ui_measurementName = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_measurementName.sizePolicy().hasHeightForWidth())
        self.ui_measurementName.setSizePolicy(sizePolicy)
        self.ui_measurementName.setObjectName(_fromUtf8("ui_measurementName"))
        self.gridLayout_4.addWidget(self.ui_measurementName, 1, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_4.addWidget(self.label_14, 2, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_4.addWidget(self.label_17, 1, 2, 1, 1)
        self.ui_experimentName = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_experimentName.sizePolicy().hasHeightForWidth())
        self.ui_experimentName.setSizePolicy(sizePolicy)
        self.ui_experimentName.setObjectName(_fromUtf8("ui_experimentName"))
        self.gridLayout_4.addWidget(self.ui_experimentName, 0, 1, 1, 3)
        self.ui_measurementCount = QtGui.QSpinBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_measurementCount.sizePolicy().hasHeightForWidth())
        self.ui_measurementCount.setSizePolicy(sizePolicy)
        self.ui_measurementCount.setMaximum(99999)
        self.ui_measurementCount.setObjectName(_fromUtf8("ui_measurementCount"))
        self.gridLayout_4.addWidget(self.ui_measurementCount, 1, 3, 1, 1)
        self.folderBrowseButton = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.folderBrowseButton.sizePolicy().hasHeightForWidth())
        self.folderBrowseButton.setSizePolicy(sizePolicy)
        self.folderBrowseButton.setObjectName(_fromUtf8("folderBrowseButton"))
        self.gridLayout_4.addWidget(self.folderBrowseButton, 2, 1, 1, 3)
        self.verticalLayout_3.addLayout(self.gridLayout_4)
        self.verticalLayout.addWidget(self.groupBox_2)
        spacerItem1 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout_4.addWidget(self.ui_settings_frame)
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.ui_stopButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_stopButton.sizePolicy().hasHeightForWidth())
        self.ui_stopButton.setSizePolicy(sizePolicy)
        self.ui_stopButton.setObjectName(_fromUtf8("ui_stopButton"))
        self.gridLayout_10.addWidget(self.ui_stopButton, 0, 1, 1, 1)
        self.ui_startButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_startButton.sizePolicy().hasHeightForWidth())
        self.ui_startButton.setSizePolicy(sizePolicy)
        self.ui_startButton.setObjectName(_fromUtf8("ui_startButton"))
        self.gridLayout_10.addWidget(self.ui_startButton, 0, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_10)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        NoiseMeasurement.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(NoiseMeasurement)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1030, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuWindow = QtGui.QMenu(self.menubar)
        self.menuWindow.setObjectName(_fromUtf8("menuWindow"))
        self.menuNotification = QtGui.QMenu(self.menubar)
        self.menuNotification.setObjectName(_fromUtf8("menuNotification"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuExperiment_Settings = QtGui.QMenu(self.menuSettings)
        self.menuExperiment_Settings.setObjectName(_fromUtf8("menuExperiment_Settings"))
        NoiseMeasurement.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(NoiseMeasurement)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        NoiseMeasurement.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(NoiseMeasurement)
        self.toolBar.setMovable(True)
        self.toolBar.setAllowedAreas(QtCore.Qt.LeftToolBarArea|QtCore.Qt.TopToolBarArea)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        NoiseMeasurement.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.actionOpen_folder = QtGui.QAction(NoiseMeasurement)
        self.actionOpen_folder.setObjectName(_fromUtf8("actionOpen_folder"))
        self.actionWorking_folder = QtGui.QAction(NoiseMeasurement)
        self.actionWorking_folder.setObjectName(_fromUtf8("actionWorking_folder"))
        self.actionLoginEmail = QtGui.QAction(NoiseMeasurement)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Icons/mail_64x64.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoginEmail.setIcon(icon)
        self.actionLoginEmail.setObjectName(_fromUtf8("actionLoginEmail"))
        self.actionHardwareSettings = QtGui.QAction(NoiseMeasurement)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Icons/settings_64x64.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHardwareSettings.setIcon(icon1)
        self.actionHardwareSettings.setObjectName(_fromUtf8("actionHardwareSettings"))
        self.actionOpenTimetraceWindow = QtGui.QAction(NoiseMeasurement)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Icons/timetrace_64x64.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenTimetraceWindow.setIcon(icon2)
        self.actionOpenTimetraceWindow.setObjectName(_fromUtf8("actionOpenTimetraceWindow"))
        self.actionOpenRealtimeNoiseWindow = QtGui.QAction(NoiseMeasurement)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Icons/realtime_noise_64x64.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenRealtimeNoiseWindow.setIcon(icon3)
        self.actionOpenRealtimeNoiseWindow.setObjectName(_fromUtf8("actionOpenRealtimeNoiseWindow"))
        self.actionAbout = QtGui.QAction(NoiseMeasurement)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Icons/info_64x64.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon4)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionOpenConsoleWindow = QtGui.QAction(NoiseMeasurement)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Icons/console_64x64.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenConsoleWindow.setIcon(icon5)
        self.actionOpenConsoleWindow.setObjectName(_fromUtf8("actionOpenConsoleWindow"))
        self.actionOpenRemote = QtGui.QAction(NoiseMeasurement)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Icons/remote_64x64.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenRemote.setIcon(icon6)
        self.actionOpenRemote.setObjectName(_fromUtf8("actionOpenRemote"))
        self.action_save_settings = QtGui.QAction(NoiseMeasurement)
        self.action_save_settings.setObjectName(_fromUtf8("action_save_settings"))
        self.action_open_settings = QtGui.QAction(NoiseMeasurement)
        self.action_open_settings.setObjectName(_fromUtf8("action_open_settings"))
        self.actionTimeInfoWindow = QtGui.QAction(NoiseMeasurement)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Icons/time_info_64x64.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTimeInfoWindow.setIcon(icon7)
        self.actionTimeInfoWindow.setObjectName(_fromUtf8("actionTimeInfoWindow"))
        self.action_what_to_do = QtGui.QAction(NoiseMeasurement)
        self.action_what_to_do.setObjectName(_fromUtf8("action_what_to_do"))
        self.actionLockScreen = QtGui.QAction(NoiseMeasurement)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Icons/lock_64x64.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLockScreen.setIcon(icon8)
        self.actionLockScreen.setObjectName(_fromUtf8("actionLockScreen"))
        self.actionThemeSwitch = QtGui.QAction(NoiseMeasurement)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Icons/theme_switch_64x64.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionThemeSwitch.setIcon(icon9)
        self.actionThemeSwitch.setObjectName(_fromUtf8("actionThemeSwitch"))
        self.actionOpenAnalysisWindow = QtGui.QAction(NoiseMeasurement)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Icons/analysis_icon_64x64.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenAnalysisWindow.setIcon(icon10)
        self.actionOpenAnalysisWindow.setObjectName(_fromUtf8("actionOpenAnalysisWindow"))
        self.actionTimetraceConversion = QtGui.QAction(NoiseMeasurement)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Icons/timetrace_conversion_v2_64x64.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTimetraceConversion.setIcon(icon11)
        self.actionTimetraceConversion.setObjectName(_fromUtf8("actionTimetraceConversion"))
        self.actionOpenPlotterWindow = QtGui.QAction(NoiseMeasurement)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Icons/plotter_icon_64x64.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenPlotterWindow.setIcon(icon12)
        self.actionOpenPlotterWindow.setObjectName(_fromUtf8("actionOpenPlotterWindow"))
        self.menuFile.addAction(self.actionOpen_folder)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionWorking_folder)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.action_what_to_do)
        self.menuWindow.addAction(self.actionOpenAnalysisWindow)
        self.menuWindow.addAction(self.actionOpenPlotterWindow)
        self.menuWindow.addAction(self.actionTimetraceConversion)
        self.menuWindow.addAction(self.actionOpenTimetraceWindow)
        self.menuWindow.addAction(self.actionOpenRealtimeNoiseWindow)
        self.menuWindow.addAction(self.actionOpenConsoleWindow)
        self.menuWindow.addAction(self.actionTimeInfoWindow)
        self.menuWindow.addAction(self.actionOpenRemote)
        self.menuWindow.addAction(self.actionLockScreen)
        self.menuWindow.addAction(self.actionThemeSwitch)
        self.menuNotification.addAction(self.actionLoginEmail)
        self.menuExperiment_Settings.addAction(self.action_open_settings)
        self.menuExperiment_Settings.addAction(self.action_save_settings)
        self.menuSettings.addAction(self.menuExperiment_Settings.menuAction())
        self.menuSettings.addAction(self.actionHardwareSettings)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuNotification.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionOpenAnalysisWindow)
        self.toolBar.addAction(self.actionLoginEmail)
        self.toolBar.addAction(self.actionOpenTimetraceWindow)
        self.toolBar.addAction(self.actionOpenRealtimeNoiseWindow)
        self.toolBar.addAction(self.actionOpenConsoleWindow)
        self.toolBar.addAction(self.actionTimeInfoWindow)
        self.toolBar.addAction(self.actionOpenRemote)
        self.toolBar.addAction(self.actionOpenPlotterWindow)
        self.toolBar.addAction(self.actionTimetraceConversion)
        self.toolBar.addAction(self.actionHardwareSettings)
        self.toolBar.addAction(self.actionLockScreen)
        self.toolBar.addAction(self.actionAbout)

        self.retranslateUi(NoiseMeasurement)
        self.ui_second_amp_coeff.setCurrentIndex(4)
        self.ui_meas_characteristic_type.setCurrentIndex(0)
        QtCore.QObject.connect(self.ui_set_temperature_single, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ui_temperature.setEnabled)
        QtCore.QObject.connect(self.ui_use_set_temperature_range, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ui_temperature.setDisabled)
        QtCore.QObject.connect(self.ui_set_drain_source_voltage, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ui_drain_source_voltage.setEnabled)
        QtCore.QObject.connect(self.ui_use_set_vds_range, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ui_drain_source_voltage.setDisabled)
        QtCore.QObject.connect(self.ui_set_gate_source_voltage, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ui_front_gate_voltage.setEnabled)
        QtCore.QObject.connect(self.ui_use_set_vfg_range, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ui_front_gate_voltage.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(NoiseMeasurement)
        NoiseMeasurement.setTabOrder(self.ui_calibrate, self.ui_open_hardware_settings)
        NoiseMeasurement.setTabOrder(self.ui_open_hardware_settings, self.ui_overload_reject)
        NoiseMeasurement.setTabOrder(self.ui_overload_reject, self.ui_simulate)
        NoiseMeasurement.setTabOrder(self.ui_simulate, self.ui_averages)
        NoiseMeasurement.setTabOrder(self.ui_averages, self.ui_use_homemade_amplifier)
        NoiseMeasurement.setTabOrder(self.ui_use_homemade_amplifier, self.ui_second_amp_coeff)
        NoiseMeasurement.setTabOrder(self.ui_second_amp_coeff, self.ui_load_resistance)
        NoiseMeasurement.setTabOrder(self.ui_load_resistance, self.ui_meas_gated_structure)
        NoiseMeasurement.setTabOrder(self.ui_meas_gated_structure, self.ui_use_dut_selector)
        NoiseMeasurement.setTabOrder(self.ui_use_dut_selector, self.ui_transistorSelector)
        NoiseMeasurement.setTabOrder(self.ui_transistorSelector, self.ui_use_automated_voltage_control)
        NoiseMeasurement.setTabOrder(self.ui_use_automated_voltage_control, self.ui_voltage_control)
        NoiseMeasurement.setTabOrder(self.ui_voltage_control, self.ui_meas_characteristic_type)
        NoiseMeasurement.setTabOrder(self.ui_meas_characteristic_type, self.ui_drain_source_voltage)
        NoiseMeasurement.setTabOrder(self.ui_drain_source_voltage, self.ui_use_set_vds_range)
        NoiseMeasurement.setTabOrder(self.ui_use_set_vds_range, self.VdsRange)
        NoiseMeasurement.setTabOrder(self.VdsRange, self.ui_front_gate_voltage)
        NoiseMeasurement.setTabOrder(self.ui_front_gate_voltage, self.ui_use_set_vfg_range)
        NoiseMeasurement.setTabOrder(self.ui_use_set_vfg_range, self.VfgRange)
        NoiseMeasurement.setTabOrder(self.VfgRange, self.ui_timetrace_mode)
        NoiseMeasurement.setTabOrder(self.ui_timetrace_mode, self.ui_timetrace_length)
        NoiseMeasurement.setTabOrder(self.ui_timetrace_length, self.ui_set_zero_after_measurement)
        NoiseMeasurement.setTabOrder(self.ui_set_zero_after_measurement, self.ui_experimentName)
        NoiseMeasurement.setTabOrder(self.ui_experimentName, self.ui_measurementName)
        NoiseMeasurement.setTabOrder(self.ui_measurementName, self.ui_measurementCount)
        NoiseMeasurement.setTabOrder(self.ui_measurementCount, self.folderBrowseButton)
        NoiseMeasurement.setTabOrder(self.folderBrowseButton, self.ui_startButton)
        NoiseMeasurement.setTabOrder(self.ui_startButton, self.ui_stopButton)
        NoiseMeasurement.setTabOrder(self.ui_stopButton, self.ui_sample_voltage_start)
        NoiseMeasurement.setTabOrder(self.ui_sample_voltage_start, self.ui_sample_voltage_end)
        NoiseMeasurement.setTabOrder(self.ui_sample_voltage_end, self.ui_front_gate_voltage_start)
        NoiseMeasurement.setTabOrder(self.ui_front_gate_voltage_start, self.ui_front_gate_voltage_end)
        NoiseMeasurement.setTabOrder(self.ui_front_gate_voltage_end, self.ui_sample_current_start)
        NoiseMeasurement.setTabOrder(self.ui_sample_current_start, self.ui_sample_current_end)
        NoiseMeasurement.setTabOrder(self.ui_sample_current_end, self.ui_sample_resistance_start)
        NoiseMeasurement.setTabOrder(self.ui_sample_resistance_start, self.ui_sample_resistance_end)
        NoiseMeasurement.setTabOrder(self.ui_sample_resistance_end, self.ui_plot)

    def retranslateUi(self, NoiseMeasurement):
        NoiseMeasurement.setWindowTitle(_translate("NoiseMeasurement", "PyFANS", None))
        self.ui_calibrate.setText(_translate("NoiseMeasurement", "Calibrate before measurement", None))
        self.ui_open_hardware_settings.setText(_translate("NoiseMeasurement", "Hardware Settings", None))
        self.ui_overload_reject.setText(_translate("NoiseMeasurement", "Overload rejection", None))
        self.ui_simulate.setText(_translate("NoiseMeasurement", "Simulate", None))
        self.label_2.setText(_translate("NoiseMeasurement", "Averages", None))
        self.ui_second_amp_coeff.setCurrentText(_translate("NoiseMeasurement", "100", None))
        self.ui_second_amp_coeff.setItemText(0, _translate("NoiseMeasurement", "1", None))
        self.ui_second_amp_coeff.setItemText(1, _translate("NoiseMeasurement", "10", None))
        self.ui_second_amp_coeff.setItemText(2, _translate("NoiseMeasurement", "20", None))
        self.ui_second_amp_coeff.setItemText(3, _translate("NoiseMeasurement", "50", None))
        self.ui_second_amp_coeff.setItemText(4, _translate("NoiseMeasurement", "100", None))
        self.ui_second_amp_coeff.setItemText(5, _translate("NoiseMeasurement", "200", None))
        self.ui_second_amp_coeff.setItemText(6, _translate("NoiseMeasurement", "500", None))
        self.ui_second_amp_coeff.setItemText(7, _translate("NoiseMeasurement", "1000", None))
        self.label_3.setText(_translate("NoiseMeasurement", "Second amplifier", None))
        self.ui_use_homemade_amplifier.setText(_translate("NoiseMeasurement", "Homemade amplifier", None))
        self.ui_temp_range_button.setText(_translate("NoiseMeasurement", "...", None))
        self.ui_temperature.setPlaceholderText(_translate("NoiseMeasurement", "temperature", None))
        self.ui_use_set_temperature_range.setText(_translate("NoiseMeasurement", "Use range", None))
        self.ui_set_temperature_single.setText(_translate("NoiseMeasurement", "Set T", None))
        self.ui_use_smart_spectrum.setText(_translate("NoiseMeasurement", "Smart Spectrum", None))
        self.ui_need_meas_temp.setText(_translate("NoiseMeasurement", "Measure Temp", None))
        self.ui_automated_temperature.setText(_translate("NoiseMeasurement", "Auto Temp", None))
        self.ui_load_resistance.setText(_translate("NoiseMeasurement", "5000", None))
        self.ui_load_resistance.setPlaceholderText(_translate("NoiseMeasurement", "resistance", None))
        self.label_4.setText(_translate("NoiseMeasurement", "Load resistance (Ω)", None))
        self.ui_use_dut_selector.setText(_translate("NoiseMeasurement", "Use DUT Selector", None))
        self.ui_transistorSelector.setText(_translate("NoiseMeasurement", "...", None))
        self.ui_meas_gated_structure.setText(_translate("NoiseMeasurement", "Gated structure", None))
        self.ui_use_automated_voltage_control.setText(_translate("NoiseMeasurement", "Automated Voltage Control", None))
        self.ui_voltage_control.setText(_translate("NoiseMeasurement", "Voltage control", None))
        self.label_18.setText(_translate("NoiseMeasurement", "Select Voltage Change Order", None))
        self.ui_meas_characteristic_type.setItemText(0, _translate("NoiseMeasurement", "Output", None))
        self.ui_meas_characteristic_type.setItemText(1, _translate("NoiseMeasurement", "Transfer", None))
        self.VfgRange.setText(_translate("NoiseMeasurement", "...", None))
        self.ui_use_set_vds_range.setText(_translate("NoiseMeasurement", "Use range", None))
        self.ui_drain_source_voltage.setPlaceholderText(_translate("NoiseMeasurement", "drain source voltage", None))
        self.VdsRange.setText(_translate("NoiseMeasurement", "...", None))
        self.ui_use_set_vfg_range.setText(_translate("NoiseMeasurement", "Use range", None))
        self.ui_front_gate_voltage.setPlaceholderText(_translate("NoiseMeasurement", "gate source voltage", None))
        self.ui_set_gate_source_voltage.setText(_translate("NoiseMeasurement", "Set Vfg", None))
        self.ui_set_drain_source_voltage.setText(_translate("NoiseMeasurement", "Set Vds", None))
        self.label.setText(_translate("NoiseMeasurement", "Write timetrace", None))
        self.ui_timetrace_mode.setItemText(0, _translate("NoiseMeasurement", "None", None))
        self.ui_timetrace_mode.setItemText(1, _translate("NoiseMeasurement", "Partial", None))
        self.ui_timetrace_mode.setItemText(2, _translate("NoiseMeasurement", "Full", None))
        self.ui_timetrace_length.setSuffix(_translate("NoiseMeasurement", " sec", None))
        self.ui_set_zero_after_measurement.setToolTip(_translate("NoiseMeasurement", "Set zero volts after measurement", None))
        self.ui_set_zero_after_measurement.setText(_translate("NoiseMeasurement", "Set zero", None))
        self.groupBox.setTitle(_translate("NoiseMeasurement", "Measurement Data", None))
        self.ui_sample_current_end.setPlaceholderText(_translate("NoiseMeasurement", "drain current end", None))
        self.label_11.setText(_translate("NoiseMeasurement", "Rsample (Ω)", None))
        self.label_7.setText(_translate("NoiseMeasurement", "End", None))
        self.label_6.setText(_translate("NoiseMeasurement", "Start", None))
        self.label_8.setText(_translate("NoiseMeasurement", "Vds (V)", None))
        self.ui_sample_current_start.setPlaceholderText(_translate("NoiseMeasurement", "drain current start", None))
        self.ui_main_voltage_end.setPlaceholderText(_translate("NoiseMeasurement", "main volt end", None))
        self.ui_sample_voltage_end.setPlaceholderText(_translate("NoiseMeasurement", "drain volt end", None))
        self.ui_main_voltage_start.setPlaceholderText(_translate("NoiseMeasurement", "main volt start", None))
        self.ui_sample_resistance_start.setPlaceholderText(_translate("NoiseMeasurement", "sample resistance ", None))
        self.label_19.setText(_translate("NoiseMeasurement", "Vmain (V)", None))
        self.ui_front_gate_voltage_start.setPlaceholderText(_translate("NoiseMeasurement", "gate volt start", None))
        self.ui_front_gate_voltage_end.setPlaceholderText(_translate("NoiseMeasurement", "gate volt end", None))
        self.label_10.setText(_translate("NoiseMeasurement", "Isample (A)", None))
        self.ui_sample_voltage_start.setPlaceholderText(_translate("NoiseMeasurement", "drain volt start", None))
        self.ui_sample_resistance_end.setPlaceholderText(_translate("NoiseMeasurement", "sample resistance", None))
        self.label_9.setText(_translate("NoiseMeasurement", "Vgs (V)", None))
        self.label_5.setText(_translate("NoiseMeasurement", "Temp (K)", None))
        self.ui_temperature_start.setPlaceholderText(_translate("NoiseMeasurement", "temperature start", None))
        self.ui_temperature_end.setPlaceholderText(_translate("NoiseMeasurement", "temperature end", None))
        self.groupBox_2.setTitle(_translate("NoiseMeasurement", "Save Data", None))
        self.label_12.setText(_translate("NoiseMeasurement", "Experiment", None))
        self.label_13.setText(_translate("NoiseMeasurement", "Measurement", None))
        self.ui_measurementName.setPlaceholderText(_translate("NoiseMeasurement", "measurement name", None))
        self.label_14.setText(_translate("NoiseMeasurement", "Folder", None))
        self.label_17.setText(_translate("NoiseMeasurement", "#", None))
        self.ui_experimentName.setPlaceholderText(_translate("NoiseMeasurement", "experiment name", None))
        self.folderBrowseButton.setText(_translate("NoiseMeasurement", "...", None))
        self.ui_stopButton.setText(_translate("NoiseMeasurement", "Stop", None))
        self.ui_startButton.setText(_translate("NoiseMeasurement", "Start", None))
        self.menuFile.setTitle(_translate("NoiseMeasurement", "File", None))
        self.menuHelp.setTitle(_translate("NoiseMeasurement", "Help", None))
        self.menuWindow.setTitle(_translate("NoiseMeasurement", "Window", None))
        self.menuNotification.setTitle(_translate("NoiseMeasurement", "Notification", None))
        self.menuSettings.setTitle(_translate("NoiseMeasurement", "Settings", None))
        self.menuExperiment_Settings.setTitle(_translate("NoiseMeasurement", "Experiment Settings", None))
        self.toolBar.setWindowTitle(_translate("NoiseMeasurement", "toolBar", None))
        self.actionOpen_folder.setText(_translate("NoiseMeasurement", "Open folder", None))
        self.actionWorking_folder.setText(_translate("NoiseMeasurement", "Working folder", None))
        self.actionLoginEmail.setText(_translate("NoiseMeasurement", "Login", None))
        self.actionLoginEmail.setToolTip(_translate("NoiseMeasurement", "Login to receive email", None))
        self.actionHardwareSettings.setText(_translate("NoiseMeasurement", "HardwareSettings", None))
        self.actionHardwareSettings.setToolTip(_translate("NoiseMeasurement", "Open hardware settings", None))
        self.actionOpenTimetraceWindow.setText(_translate("NoiseMeasurement", "Timetrace", None))
        self.actionOpenRealtimeNoiseWindow.setText(_translate("NoiseMeasurement", "Realtime Noise", None))
        self.actionAbout.setText(_translate("NoiseMeasurement", "About", None))
        self.actionOpenConsoleWindow.setText(_translate("NoiseMeasurement", "Console", None))
        self.actionOpenConsoleWindow.setToolTip(_translate("NoiseMeasurement", "Open console window", None))
        self.actionOpenRemote.setText(_translate("NoiseMeasurement", "Remote", None))
        self.actionOpenRemote.setToolTip(_translate("NoiseMeasurement", "Starts remote access", None))
        self.action_save_settings.setText(_translate("NoiseMeasurement", "Save", None))
        self.action_open_settings.setText(_translate("NoiseMeasurement", "Open", None))
        self.actionTimeInfoWindow.setText(_translate("NoiseMeasurement", "TimeInfo", None))
        self.action_what_to_do.setText(_translate("NoiseMeasurement", "Что же делать?", None))
        self.actionLockScreen.setText(_translate("NoiseMeasurement", "Lock Screen", None))
        self.actionLockScreen.setToolTip(_translate("NoiseMeasurement", "Lock window", None))
        self.actionThemeSwitch.setText(_translate("NoiseMeasurement", "Theme Switch", None))
        self.actionOpenAnalysisWindow.setText(_translate("NoiseMeasurement", "Open Analysis Window", None))
        self.actionOpenAnalysisWindow.setToolTip(_translate("NoiseMeasurement", "Opens window for data analysis", None))
        self.actionTimetraceConversion.setText(_translate("NoiseMeasurement", "TimetraceConversion", None))
        self.actionOpenPlotterWindow.setText(_translate("NoiseMeasurement", "OpenPlotterWindow", None))

from pyqtgraph import GraphicsLayoutWidget
from . import icon_resources_rc
