# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Programming\Repositories\PyFANS\PyFANS\UI\UI_HardwareSettings_v3.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_HardwareSettings(object):
    def setupUi(self, HardwareSettings):
        HardwareSettings.setObjectName(_fromUtf8("HardwareSettings"))
        HardwareSettings.resize(365, 457)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Icons/settings_64x64.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        HardwareSettings.setWindowIcon(icon)
        self.gridLayout_2 = QtGui.QGridLayout(HardwareSettings)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_4 = QtGui.QLabel(HardwareSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.ui_fans_controller = QtGui.QComboBox(HardwareSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_fans_controller.sizePolicy().hasHeightForWidth())
        self.ui_fans_controller.setSizePolicy(sizePolicy)
        self.ui_fans_controller.setObjectName(_fromUtf8("ui_fans_controller"))
        self.gridLayout_2.addWidget(self.ui_fans_controller, 0, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(HardwareSettings)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.ui_sample_relay = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_sample_relay.sizePolicy().hasHeightForWidth())
        self.ui_sample_relay.setSizePolicy(sizePolicy)
        self.ui_sample_relay.setObjectName(_fromUtf8("ui_sample_relay"))
        self.ui_sample_relay.addItem(_fromUtf8(""))
        self.ui_sample_relay.addItem(_fromUtf8(""))
        self.ui_sample_relay.addItem(_fromUtf8(""))
        self.ui_sample_relay.addItem(_fromUtf8(""))
        self.ui_sample_relay.addItem(_fromUtf8(""))
        self.ui_sample_relay.addItem(_fromUtf8(""))
        self.ui_sample_relay.addItem(_fromUtf8(""))
        self.ui_sample_relay.addItem(_fromUtf8(""))
        self.ui_sample_relay.addItem(_fromUtf8(""))
        self.ui_sample_relay.addItem(_fromUtf8(""))
        self.ui_sample_relay.addItem(_fromUtf8(""))
        self.ui_sample_relay.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.ui_sample_relay, 1, 1, 1, 1)
        self.ui_gate_channel = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_gate_channel.sizePolicy().hasHeightForWidth())
        self.ui_gate_channel.setSizePolicy(sizePolicy)
        self.ui_gate_channel.setObjectName(_fromUtf8("ui_gate_channel"))
        self.ui_gate_channel.addItem(_fromUtf8(""))
        self.ui_gate_channel.addItem(_fromUtf8(""))
        self.ui_gate_channel.addItem(_fromUtf8(""))
        self.ui_gate_channel.addItem(_fromUtf8(""))
        self.ui_gate_channel.addItem(_fromUtf8(""))
        self.ui_gate_channel.addItem(_fromUtf8(""))
        self.ui_gate_channel.addItem(_fromUtf8(""))
        self.ui_gate_channel.addItem(_fromUtf8(""))
        self.ui_gate_channel.addItem(_fromUtf8(""))
        self.ui_gate_channel.addItem(_fromUtf8(""))
        self.ui_gate_channel.addItem(_fromUtf8(""))
        self.ui_gate_channel.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.ui_gate_channel, 2, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.ui_gate_relay = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_gate_relay.sizePolicy().hasHeightForWidth())
        self.ui_gate_relay.setSizePolicy(sizePolicy)
        self.ui_gate_relay.setObjectName(_fromUtf8("ui_gate_relay"))
        self.ui_gate_relay.addItem(_fromUtf8(""))
        self.ui_gate_relay.addItem(_fromUtf8(""))
        self.ui_gate_relay.addItem(_fromUtf8(""))
        self.ui_gate_relay.addItem(_fromUtf8(""))
        self.ui_gate_relay.addItem(_fromUtf8(""))
        self.ui_gate_relay.addItem(_fromUtf8(""))
        self.ui_gate_relay.addItem(_fromUtf8(""))
        self.ui_gate_relay.addItem(_fromUtf8(""))
        self.ui_gate_relay.addItem(_fromUtf8(""))
        self.ui_gate_relay.addItem(_fromUtf8(""))
        self.ui_gate_relay.addItem(_fromUtf8(""))
        self.ui_gate_relay.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.ui_gate_relay, 3, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.ui_sample_channel = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_sample_channel.sizePolicy().hasHeightForWidth())
        self.ui_sample_channel.setSizePolicy(sizePolicy)
        self.ui_sample_channel.setObjectName(_fromUtf8("ui_sample_channel"))
        self.ui_sample_channel.addItem(_fromUtf8(""))
        self.ui_sample_channel.addItem(_fromUtf8(""))
        self.ui_sample_channel.addItem(_fromUtf8(""))
        self.ui_sample_channel.addItem(_fromUtf8(""))
        self.ui_sample_channel.addItem(_fromUtf8(""))
        self.ui_sample_channel.addItem(_fromUtf8(""))
        self.ui_sample_channel.addItem(_fromUtf8(""))
        self.ui_sample_channel.addItem(_fromUtf8(""))
        self.ui_sample_channel.addItem(_fromUtf8(""))
        self.ui_sample_channel.addItem(_fromUtf8(""))
        self.ui_sample_channel.addItem(_fromUtf8(""))
        self.ui_sample_channel.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.ui_sample_channel, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 2)
        self.groupBox_2 = QtGui.QGroupBox(HardwareSettings)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.ui_acquisition_channel = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_acquisition_channel.sizePolicy().hasHeightForWidth())
        self.ui_acquisition_channel.setSizePolicy(sizePolicy)
        self.ui_acquisition_channel.setObjectName(_fromUtf8("ui_acquisition_channel"))
        self.ui_acquisition_channel.addItem(_fromUtf8(""))
        self.ui_acquisition_channel.addItem(_fromUtf8(""))
        self.ui_acquisition_channel.addItem(_fromUtf8(""))
        self.ui_acquisition_channel.addItem(_fromUtf8(""))
        self.ui_acquisition_channel.addItem(_fromUtf8(""))
        self.ui_acquisition_channel.addItem(_fromUtf8(""))
        self.ui_acquisition_channel.addItem(_fromUtf8(""))
        self.ui_acquisition_channel.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.ui_acquisition_channel, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 1, 0, 1, 1)
        self.ui_sample_feedback_channel = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_sample_feedback_channel.sizePolicy().hasHeightForWidth())
        self.ui_sample_feedback_channel.setSizePolicy(sizePolicy)
        self.ui_sample_feedback_channel.setObjectName(_fromUtf8("ui_sample_feedback_channel"))
        self.ui_sample_feedback_channel.addItem(_fromUtf8(""))
        self.ui_sample_feedback_channel.addItem(_fromUtf8(""))
        self.ui_sample_feedback_channel.addItem(_fromUtf8(""))
        self.ui_sample_feedback_channel.addItem(_fromUtf8(""))
        self.ui_sample_feedback_channel.addItem(_fromUtf8(""))
        self.ui_sample_feedback_channel.addItem(_fromUtf8(""))
        self.ui_sample_feedback_channel.addItem(_fromUtf8(""))
        self.ui_sample_feedback_channel.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.ui_sample_feedback_channel, 1, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 2, 0, 1, 1)
        self.ui_gate_feedback_channel = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_gate_feedback_channel.sizePolicy().hasHeightForWidth())
        self.ui_gate_feedback_channel.setSizePolicy(sizePolicy)
        self.ui_gate_feedback_channel.setObjectName(_fromUtf8("ui_gate_feedback_channel"))
        self.ui_gate_feedback_channel.addItem(_fromUtf8(""))
        self.ui_gate_feedback_channel.addItem(_fromUtf8(""))
        self.ui_gate_feedback_channel.addItem(_fromUtf8(""))
        self.ui_gate_feedback_channel.addItem(_fromUtf8(""))
        self.ui_gate_feedback_channel.addItem(_fromUtf8(""))
        self.ui_gate_feedback_channel.addItem(_fromUtf8(""))
        self.ui_gate_feedback_channel.addItem(_fromUtf8(""))
        self.ui_gate_feedback_channel.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.ui_gate_feedback_channel, 2, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 3, 0, 1, 1)
        self.ui_main_feedback_channel = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_main_feedback_channel.sizePolicy().hasHeightForWidth())
        self.ui_main_feedback_channel.setSizePolicy(sizePolicy)
        self.ui_main_feedback_channel.setObjectName(_fromUtf8("ui_main_feedback_channel"))
        self.ui_main_feedback_channel.addItem(_fromUtf8(""))
        self.ui_main_feedback_channel.addItem(_fromUtf8(""))
        self.ui_main_feedback_channel.addItem(_fromUtf8(""))
        self.ui_main_feedback_channel.addItem(_fromUtf8(""))
        self.ui_main_feedback_channel.addItem(_fromUtf8(""))
        self.ui_main_feedback_channel.addItem(_fromUtf8(""))
        self.ui_main_feedback_channel.addItem(_fromUtf8(""))
        self.ui_main_feedback_channel.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.ui_main_feedback_channel, 3, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 2, 0, 1, 2)
        self.buttonBox = QtGui.QDialogButtonBox(HardwareSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_2.addWidget(self.buttonBox, 3, 0, 1, 2)

        self.retranslateUi(HardwareSettings)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), HardwareSettings.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), HardwareSettings.reject)
        QtCore.QMetaObject.connectSlotsByName(HardwareSettings)

    def retranslateUi(self, HardwareSettings):
        HardwareSettings.setWindowTitle(_translate("HardwareSettings", "Dialog", None))
        self.label_4.setText(_translate("HardwareSettings", "FANS Controller", None))
        self.groupBox.setTitle(_translate("HardwareSettings", "Output channels", None))
        self.label_7.setText(_translate("HardwareSettings", "Sample Relay", None))
        self.ui_sample_relay.setItemText(0, _translate("HardwareSettings", "1", None))
        self.ui_sample_relay.setItemText(1, _translate("HardwareSettings", "2", None))
        self.ui_sample_relay.setItemText(2, _translate("HardwareSettings", "3", None))
        self.ui_sample_relay.setItemText(3, _translate("HardwareSettings", "4", None))
        self.ui_sample_relay.setItemText(4, _translate("HardwareSettings", "5", None))
        self.ui_sample_relay.setItemText(5, _translate("HardwareSettings", "6", None))
        self.ui_sample_relay.setItemText(6, _translate("HardwareSettings", "7", None))
        self.ui_sample_relay.setItemText(7, _translate("HardwareSettings", "8", None))
        self.ui_sample_relay.setItemText(8, _translate("HardwareSettings", "9", None))
        self.ui_sample_relay.setItemText(9, _translate("HardwareSettings", "10", None))
        self.ui_sample_relay.setItemText(10, _translate("HardwareSettings", "11", None))
        self.ui_sample_relay.setItemText(11, _translate("HardwareSettings", "12", None))
        self.ui_gate_channel.setItemText(0, _translate("HardwareSettings", "1", None))
        self.ui_gate_channel.setItemText(1, _translate("HardwareSettings", "2", None))
        self.ui_gate_channel.setItemText(2, _translate("HardwareSettings", "3", None))
        self.ui_gate_channel.setItemText(3, _translate("HardwareSettings", "4", None))
        self.ui_gate_channel.setItemText(4, _translate("HardwareSettings", "5", None))
        self.ui_gate_channel.setItemText(5, _translate("HardwareSettings", "6", None))
        self.ui_gate_channel.setItemText(6, _translate("HardwareSettings", "7", None))
        self.ui_gate_channel.setItemText(7, _translate("HardwareSettings", "8", None))
        self.ui_gate_channel.setItemText(8, _translate("HardwareSettings", "9", None))
        self.ui_gate_channel.setItemText(9, _translate("HardwareSettings", "10", None))
        self.ui_gate_channel.setItemText(10, _translate("HardwareSettings", "11", None))
        self.ui_gate_channel.setItemText(11, _translate("HardwareSettings", "12", None))
        self.label_6.setText(_translate("HardwareSettings", "Gate Channel", None))
        self.ui_gate_relay.setItemText(0, _translate("HardwareSettings", "1", None))
        self.ui_gate_relay.setItemText(1, _translate("HardwareSettings", "2", None))
        self.ui_gate_relay.setItemText(2, _translate("HardwareSettings", "3", None))
        self.ui_gate_relay.setItemText(3, _translate("HardwareSettings", "4", None))
        self.ui_gate_relay.setItemText(4, _translate("HardwareSettings", "5", None))
        self.ui_gate_relay.setItemText(5, _translate("HardwareSettings", "6", None))
        self.ui_gate_relay.setItemText(6, _translate("HardwareSettings", "7", None))
        self.ui_gate_relay.setItemText(7, _translate("HardwareSettings", "8", None))
        self.ui_gate_relay.setItemText(8, _translate("HardwareSettings", "9", None))
        self.ui_gate_relay.setItemText(9, _translate("HardwareSettings", "10", None))
        self.ui_gate_relay.setItemText(10, _translate("HardwareSettings", "11", None))
        self.ui_gate_relay.setItemText(11, _translate("HardwareSettings", "12", None))
        self.label_8.setText(_translate("HardwareSettings", "Gate Relay", None))
        self.label_5.setText(_translate("HardwareSettings", "Sample Channel", None))
        self.ui_sample_channel.setItemText(0, _translate("HardwareSettings", "1", None))
        self.ui_sample_channel.setItemText(1, _translate("HardwareSettings", "2", None))
        self.ui_sample_channel.setItemText(2, _translate("HardwareSettings", "3", None))
        self.ui_sample_channel.setItemText(3, _translate("HardwareSettings", "4", None))
        self.ui_sample_channel.setItemText(4, _translate("HardwareSettings", "5", None))
        self.ui_sample_channel.setItemText(5, _translate("HardwareSettings", "6", None))
        self.ui_sample_channel.setItemText(6, _translate("HardwareSettings", "7", None))
        self.ui_sample_channel.setItemText(7, _translate("HardwareSettings", "8", None))
        self.ui_sample_channel.setItemText(8, _translate("HardwareSettings", "9", None))
        self.ui_sample_channel.setItemText(9, _translate("HardwareSettings", "10", None))
        self.ui_sample_channel.setItemText(10, _translate("HardwareSettings", "11", None))
        self.ui_sample_channel.setItemText(11, _translate("HardwareSettings", "12", None))
        self.groupBox_2.setTitle(_translate("HardwareSettings", "Input channels", None))
        self.label_9.setText(_translate("HardwareSettings", "Acquisition channel", None))
        self.ui_acquisition_channel.setItemText(0, _translate("HardwareSettings", "1", None))
        self.ui_acquisition_channel.setItemText(1, _translate("HardwareSettings", "2", None))
        self.ui_acquisition_channel.setItemText(2, _translate("HardwareSettings", "3", None))
        self.ui_acquisition_channel.setItemText(3, _translate("HardwareSettings", "4", None))
        self.ui_acquisition_channel.setItemText(4, _translate("HardwareSettings", "5", None))
        self.ui_acquisition_channel.setItemText(5, _translate("HardwareSettings", "6", None))
        self.ui_acquisition_channel.setItemText(6, _translate("HardwareSettings", "7", None))
        self.ui_acquisition_channel.setItemText(7, _translate("HardwareSettings", "8", None))
        self.label_10.setText(_translate("HardwareSettings", "Sample feedback", None))
        self.ui_sample_feedback_channel.setItemText(0, _translate("HardwareSettings", "1", None))
        self.ui_sample_feedback_channel.setItemText(1, _translate("HardwareSettings", "2", None))
        self.ui_sample_feedback_channel.setItemText(2, _translate("HardwareSettings", "3", None))
        self.ui_sample_feedback_channel.setItemText(3, _translate("HardwareSettings", "4", None))
        self.ui_sample_feedback_channel.setItemText(4, _translate("HardwareSettings", "5", None))
        self.ui_sample_feedback_channel.setItemText(5, _translate("HardwareSettings", "6", None))
        self.ui_sample_feedback_channel.setItemText(6, _translate("HardwareSettings", "7", None))
        self.ui_sample_feedback_channel.setItemText(7, _translate("HardwareSettings", "8", None))
        self.label_11.setText(_translate("HardwareSettings", "Gate feedback", None))
        self.ui_gate_feedback_channel.setItemText(0, _translate("HardwareSettings", "1", None))
        self.ui_gate_feedback_channel.setItemText(1, _translate("HardwareSettings", "2", None))
        self.ui_gate_feedback_channel.setItemText(2, _translate("HardwareSettings", "3", None))
        self.ui_gate_feedback_channel.setItemText(3, _translate("HardwareSettings", "4", None))
        self.ui_gate_feedback_channel.setItemText(4, _translate("HardwareSettings", "5", None))
        self.ui_gate_feedback_channel.setItemText(5, _translate("HardwareSettings", "6", None))
        self.ui_gate_feedback_channel.setItemText(6, _translate("HardwareSettings", "7", None))
        self.ui_gate_feedback_channel.setItemText(7, _translate("HardwareSettings", "8", None))
        self.label_12.setText(_translate("HardwareSettings", "Main feedback", None))
        self.ui_main_feedback_channel.setItemText(0, _translate("HardwareSettings", "1", None))
        self.ui_main_feedback_channel.setItemText(1, _translate("HardwareSettings", "2", None))
        self.ui_main_feedback_channel.setItemText(2, _translate("HardwareSettings", "3", None))
        self.ui_main_feedback_channel.setItemText(3, _translate("HardwareSettings", "4", None))
        self.ui_main_feedback_channel.setItemText(4, _translate("HardwareSettings", "5", None))
        self.ui_main_feedback_channel.setItemText(5, _translate("HardwareSettings", "6", None))
        self.ui_main_feedback_channel.setItemText(6, _translate("HardwareSettings", "7", None))
        self.ui_main_feedback_channel.setItemText(7, _translate("HardwareSettings", "8", None))

from . import icon_resources_rc
